### ISSUE TITLE
feature: Show the panel on the side

### ISSUE THREAD

**Issue by marcinjahn** [oae/gnome-shell-pano#10]
Currently, the panel can only be displayed at the bottom of the screen. It would be great to have the ability to choose a different location - like left/rigtht side of the screen.

I guess this extensions was inspired by https://pasteapp.io/. There's actually an even better app - https://onmyway133.com/pastepal/. I think Pano would benefit a lot if it took some inspiration from PastePal. It allows you to choose any side for the panel to appear at. It also has other features that I'm going to propose as features in separate "Issues".

Btw, great work! I've been waiting for such an extension.

**Comment by oae** [comment]
> Btw, great work! I've been waiting for such an extension.

Thank you. I have been waiting too. That is why I made :smile: 

I will consider this feature.

**Comment by jdoss** [comment]
Something like a drop down like gpaste would be pretty nice. 

![image](https://user-images.githubusercontent.com/8195/187557097-77b0c5cf-bc6e-454a-8ee8-11e192cafd7b.png)

**Comment by marcinjahn** [comment]
> Something like a drop down like gpaste would be pretty nice.
> 
> ![image](https://user-images.githubusercontent.com/8195/187557097-77b0c5cf-bc6e-454a-8ee8-11e192cafd7b.png)

If you want such a layout, why not continue using gpaste?

I'd rather advise to continue with the same look as it is now, just use column instead of a row.
