### ISSUE TITLE
Gnome 43 crash with pano enabled and something related to libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.

### ISSUE THREAD

**Issue by truongan** [oae/gnome-shell-pano#103]
**Describe the bug**
Have gnome 43 on archlinux with fcgur repository. The gnome shell sessions crash right after I install pano, logout then log back in. 
After the crash, Gnome will default back to all extension disabled. 
If I then enable all extension back on, the session will crash again. 

**To Reproduce**
- GNOME Shell version: 3
- Distro: Archlinux
- Steps to reproduce, if applicable:
1. Install pano (unzip the file [https://github.com/oae/gnome-shell-pano/archive/refs/tags/v10.zip](https://github.com/oae/gnome-shell-pano/archive/refs/tags/v10.zip) into `~/.local/share/gnome-shell/extensions`)
2. Enabled pano
3. Gnome-shell sessions CRASHED. I got thrown back into gdm login screen, with all my extension disabled
4. Log back in from gdm screen
5. Re-enabled extension
6. Gnome-shell crash again, back to step 3.

**Log data**
The time of one of the crashes
```
Thg 9 30 23:07:51 anhomepc systemd-coredump[852789]: [🡕] Process 849381 (gnome-shell) of user 1000 dumped core.
                                                     
                                                     Module linux-vdso.so.1 with build-id 72ca08d939503339fc5dcba9ae5c75d2b279b7ec
                                                     Module libsoup-2.4.so.1 with build-id 678dafa54638a6d0ab73f810643f9a23d988db00
```
Output from `journalctl /usr/bin/gnome-shell` just before that time :
```
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: == Stack trace for context 0x55d6880ca190 ==
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #0   55d688624268 i   /home/truongan/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:697 (11a101122a60 @ 72)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #1   55d6886241d8 i   /home/truongan/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:703 (11a101122ab0 @ 17)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #2   55d688624138 i   /home/truongan/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:16613 (3c8f0e03fba0 @ 57)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #3   55d6886240b0 i   /home/truongan/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:16774 (3c8f0e049150 @ 30)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #4   55d688623fd0 i   resource:///org/gnome/shell/ui/extensionSystem.js:465 (165ce3f19880 @ 376)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #5   7fff56509a70 b   resource:///org/gnome/shell/ui/extensionSystem.js:162 (165ce3f19330 @ 145)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #6   55d688623f48 i   resource:///org/gnome/shell/ui/extensionSystem.js:529 (165ce3f19b00 @ 15)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #7   7fff5650a430 b   self-hosted:164 (3a470d68c330 @ 272)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #8   55d688623ec0 i   resource:///org/gnome/shell/ui/extensionSystem.js:529 (165ce3f19a60 @ 65)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #9   55d688623e38 i   resource:///org/gnome/shell/ui/extensionSystem.js:517 (165ce3f19a10 @ 17)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #10   7fff5650add0 b   self-hosted:1115 (3a470d67eec0 @ 463)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #11   7fff5650c5d0 b   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:685 (3a470d6a00b0 @ 169)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #12   55d688623da8 i   resource:///org/gnome/shell/ui/shellDBus.js:482 (3ce62e86a100 @ 26)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #13   55d688623d10 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:388 (3a470d69f560 @ 26)
Thg 9 30 23:07:49 anhomepc gnome-shell[849381]: #14   55d688623c68 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:407 (3a470d69f6a0 @ 31)
Thg 9 30 23:07:49 anhomepc audit[849381]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=13 pid=849381 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=5 res=1
Thg 9 30 23:07:51 anhomepc gnome-shell[852927]: Running GNOME Shell (using mutter 43.0) as a X11 window and compositing manager

```

**Comment by lqs01** [comment]
I had the same problem. Did you install the libgda6 package? This solves the problem for me.

**Comment by truongan** [comment]
> 

Wow, that was spot on. I used to have arch's `community/libgda 5.2.10-3` installed, as per instruction. After I replaced it with `fcgu/libgda6` pano seem to work now. 

Perhaps some insight should be availabe on the READ.me, then we can close this issue.

**Comment by AdsonCicilioti** [comment]
Install an another lib version from an alternative repository not is a good solution for Arch users with Gnome 43.
The Gnome 43 arrives today on Arch and i need unistall Pano extension to still use Gnome 43.

Awaiting an good solution from extension author.

**Comment by oae** [comment]
Using libgda5 and gnome 43 is in conflict and crashes the gnome-shell. Arch Linux from the fcgu repo is not complete. You either install libgda6 (and remove libgda6) or wait for the official gnome packages to upgrade it.

**Comment by underdoeg** [comment]
This PKGBUILD allowed me to install libgda6 in arch and use the extension again https://gist.github.com/underdoeg/db2b2e6d357e3cb7fdd94ae526fab6b9

**Comment by truongan** [comment]
I saw a new libgda6 package on Arch's official community repository today, still fresh: 
https://archlinux.org/packages/community/x86_64/libgda6/
Last Packager: 	[Antonio Rojas](https://archlinux.org/packages/?packager=arojas)
Will try it out and report back

**Comment by AdsonCicilioti** [comment]
> 

Thx @truongan !
I'll try it

**Comment by AdsonCicilioti** [comment]
The new `libgda6` from community repo fix it!

**Comment by truongan** [comment]
I think that's settled it then. This issue is quite arch's specific and has been fully resolved.

**Comment by kfirufk** [comment]
same libsoup issue on gentoo, there is no libgda6 package. i'll try to see if i can get it installed manually and see if it solves it in this case as well.
