### ISSUE TITLE
Bug with selecting text containing escape character `\`

### ISSUE THREAD

**Issue by naiiren** [oae/gnome-shell-pano#107]
- GNOME Shell version: 42
- Distro: Ubuntu 22.04
- Pano version: 10

For a piece of text containing the escape character '\\', each time I select it in the panel, the number of '\\' just doubles. Here are the screenshots:

- original text: ![image](https://user-images.githubusercontent.com/16153455/194687878-4cfc9b2b-2ab0-446e-9db8-43f35dfea914.png)

- select once: ![image](https://user-images.githubusercontent.com/16153455/194687927-dc4aa35b-6de9-423f-a394-b0013031aaa8.png)

- and more: ![image](https://user-images.githubusercontent.com/16153455/194687939-a456be0d-225d-4c91-862b-972764d44967.png)

**Comment by EmixamPP** [comment]
I confirm that bug, and it is very annoying :'(

**Comment by Totto16** [comment]
Same here, it is really, especially when working with latex 🤦🏼‍♂️

**Comment by e2ipi-1** [comment]
A workaround is proposed [here](https://github.com/oae/gnome-shell-pano/issues/196#issuecomment-1925423080)

**Comment by Totto16** [comment]
@e2ipi-1 @EmixamPP @naiiren 
I made a PR that fixes this #266 
It would really help if you tested it locally, by following the steps in the [README](https://github.com/oae/gnome-shell-pano?tab=readme-ov-file#development) ❤️
