### ISSUE TITLE
Add more translatable strings

### ISSUE THREAD

**Issue by rene-coty** [oae/gnome-shell-pano#108]
Some items of the UI can't be translated such as : the type of the clipboard's content (e.g.: "file", "code", "link", "text") and the indicator that shows when the content has been copied to the clipboard (e.g.: "1 hour ago"). As they are not translatable, these strings will only appear in English, which can be confusing when the rest of the app has been localized _See screenshot below_

![Capture d’écran du 2022-10-09 11-49-05](https://user-images.githubusercontent.com/95506494/194750367-a154e86b-a678-4367-9722-72ae98c5c9b8.png)

**Comment by oae** [comment]
I have added translation strings for titles and used already translated date-related strings.
