### ISSUE TITLE
Feature request: open link in default browser

### ISSUE THREAD

**Issue by Microwave-WYB** [oae/gnome-shell-pano#109]
**Is your feature request related to a problem? Please describe.**
It would be a big plus if we can navigate to the website using the default browser directly from pano. The thumbnails also give you an intuition of doing that.

**Describe the solution you'd like**
Add a clickable link or click with`Ctrl` to open the link.

**Comment by oae** [comment]
I have added the `Open Links in Browser` option. If it is enabled, pano will open the link with the default browser.

![image](https://user-images.githubusercontent.com/1043714/222932228-f7ba3a94-073a-4c79-a98a-62c896cf84c2.png)
