### ISSUE TITLE
feature: Show the icon of an app where the entity comes from

### ISSUE THREAD

**Issue by marcinjahn** [oae/gnome-shell-pano#11]
It would be nice to see a small icon of an app where a given copied item comes from. It would help to distinguish the items on the list a bit.

Feature inspired by https://onmyway133.com/pastepal/.

**Comment by marcinjahn** [comment]
I'm not sure if that's even possible, do the copied items have an information about the source where they come from?

**Comment by rmnscnce** [comment]
In reply to @marcinjahn:
> do the copied items have an information about the source where they come from

No, but it's straightforward to implement using the Shell API by querying the active window information when the copy request was done and then appending it into the ClipboardContent object. Sure, it will slow down the process but it should be negligible (it's probably how PastePal does it on macOS as well -- same concept with a different implementation detail).

**Comment by oae** [comment]
Thank you for the suggestion. I will look into it.

**Comment by oae** [comment]
As I checked, gnome-shell clipboard API doesn't expose the owner of the clipboard. Only relying on the focused window can be inconsistent. So I will not be implementing this feature.
