### ISSUE TITLE
Option to open Pano with hot edge

### ISSUE THREAD

**Issue by forteller** [oae/gnome-shell-pano#111]
If you're working with something where you have to copy and paste a lot of things, then opening Pano fast with the mouse would be useful. A hot edge, where when you press the mouse cursor downward on the bottom edge of the screen to open Pano, would be a great way to implement this, I think.

Seeing as this might be most useful only in periods when working with a lot of copy/paste, and otherwise might not be as good, some sort of checkbox or other way of turning it on and off in the Pano UI itself might be ideal.

Just a though, I hope you like. Thanks for a great extension I use all day, every day! :)

**Comment by oae** [comment]
I have exposed some dbus methods. You can automate window visibility however you like. See https://github.com/oae/gnome-shell-pano#cli
