### ISSUE TITLE
Can't build project from source

### ISSUE THREAD

**Issue by felipedobrinin** [oae/gnome-shell-pano#116]
Running on Nobara based on Fedora
![image](https://user-images.githubusercontent.com/78673467/199152606-5145ccb0-3702-446d-a9e2-187c49f9dbac.png)
Yarn asks for Cogl and Gda but both are already installed. 
![image](https://user-images.githubusercontent.com/78673467/199152724-dd5db535-4ec1-45b8-86ca-14b5f835ed5c.png)
Is the package another ?

**Comment by oae** [comment]
You need to have the versions specified under `docs.json`
https://github.com/oae/gnome-shell-pano/blob/68cabe73156796010c353435a497da3706ffd066/docs.json#L14-L16

**Comment by oae** [comment]
If you want to build against libgda5, you need to revert this change. https://github.com/oae/gnome-shell-pano/commit/555b2a0b55d11bd064a07d8a7e6d2412c96c248c#diff-c4cfad04b9f62b20d9141495f53f8de26fc152fd01be698129e5d0a1dca76491
