### ISSUE TITLE
Option to open on top of fullscreen apps

### ISSUE THREAD

**Issue by shetozz** [oae/gnome-shell-pano#119]
When opening pano with a fullscreen app it doesn't show until you get out of fullscreen mode.

Idk if it's fixable tbh.

**Comment by truongan** [comment]
I can't think of any other clipboard manager that can or should operate on top of full screen apps. They are full screen for a reason, and if you really need clipboard during that time, can't a quick switch between windows suffice ?

**Comment by tennox** [comment]
I often open my IDE in fullscreen to use all available screen real-estate. I also love to use pano - but currently when I open it on the screen with the fullscreen app it just shortly flashes and disappears :cry:

**Comment by shetozz** [comment]
@tennox , it's a similar use case, but unfortunately this issue got closed, as not planned, so we're out of luck.
