### ISSUE TITLE
Exclude password from being stored

### ISSUE THREAD

**Issue by BarbzYHOOL** [oae/gnome-shell-pano#121]
**Is your feature request related to a problem? Please describe.**
When I use `pass` in my terminal, it copies the password to the clipboard which is not secure.

**Describe the solution you'd like**
Exclude password from being stored, dunno how you could do that. For CopyQ, there is an extension to pass and I feel like going with that https://github.com/vy/pass-extension-copyq but i prefer Pano 

**Describe alternatives you've considered**
I tried to exclude my terminal name "Tilix", the name of the window as well, but it keeps storing it

**Additional context**

**Comment by oae** [comment]
This is currently not possible. Could you try adding the class name of the application to exclude apps? You can use `xprop` to get the class name. Other than this, there is no other way to exclude apps for now.

**Comment by BarbzYHOOL** [comment]
? I don't use a KDE password manager, I use a terminal app called "pass", therefore the window is the terminal aka "Tilix" in my case

xprop returns: WM_CLASS(STRING) = "tilix", "Tilix"

but I already tried to put `tilix` with no success

Did I try it right?

**Comment by oae** [comment]
Can you try `Tilix`

**Comment by oae** [comment]
> ? I don't use a KDE password manager, I use a terminal app called "pass"

I meant if you set the mime type for the clipboard to `x-kde-passwordManagerHint`, pano will not track it. You can try it the following example

```sh
echo "secret" | xclip -sel clip -t "x-kde-passwordManagerHint"
```

I don't know how pass works but if you can get output and copy it like above example, pano will not save it.

**Comment by BarbzYHOOL** [comment]
> Can you try `Tilix`?

This works but it excludes any copying I make inside Tilix (but it still copies, which is cool)



> > ? I don't use a KDE password manager, I use a terminal app called "pass"
> 
> I meant if you set the mime type for the clipboard to `x-kde-passwordManagerHint`, pano will not track it. You can try it with the following example
> 
> ```shell
> echo "secret" | xclip -sel clip -t "x-kde-passwordManagerHint"
> ```
> 
> I don't know how pass works but if you can get output and copy it like the above example, pano will not save it. In this way, you don't need to exclude the tilix.


I don't understand, set the mime type for the clipboard??? what does it even mean?
I don't understand the example but that sounds interesting, if we figure it out it could be added to the description/FAQ of PANO

@oae

**Comment by BarbzYHOOL** [comment]
Since I used your command `echo "secret" | xclip -sel clip -t "x-kde-passwordManagerHint"` now pano no longers works, it's totally empty :(
