### ISSUE TITLE
Tabs to save some pastable content

### ISSUE THREAD

**Issue by BarbzYHOOL** [oae/gnome-shell-pano#122]
Like in CopyQ, a way to store some content for later usage. Can be quite useful

**Comment by oae** [comment]
Now you can pin items with `ctrl` + `s` or using :star: icon and switch between all items/favorites with `alt` key
![image](https://user-images.githubusercontent.com/1043714/222009351-0d20452b-ebfe-419e-936c-b49a2f8d92fa.png)
