### ISSUE TITLE
Configure size of the clipboard cards

### ISSUE THREAD

**Issue by BarbzYHOOL** [oae/gnome-shell-pano#123]
**Is your feature request related to a problem? Please describe.**
It's a bit huge

**Describe the solution you'd like**
A way to reduce the size of the cards maybe (or to increase to full screen)

**Comment by davemosk** [comment]
I'd love to see this feature too.

**Comment by oae** [comment]
The new version will include this option

![image](https://user-images.githubusercontent.com/1043714/221446111-d74089ad-21ce-4ad8-a474-d7b52ec7db24.png)
