### ISSUE TITLE
It is difficult to paste into the correct window when using Gnome's active window follows cursor option

### ISSUE THREAD

**Issue by MiguelGuthridge** [oae/gnome-shell-pano#125]
**Describe the bug**
When I enable Gnome's "Active window follows cursor" option, Pano often pastes into the wrong window. This is because in order to click the correct clipboard entry, I need to move my mouse away from the window I wish to paste in, meaning when Pano's panel closes, the wrong window will be chosen by Gnome as the selection, meaning that the content will be pasted into the wrong place.

**Expected behavior**
I would expect Pano to check the active window as it opens, then paste into that window as it closes, rather than just pasting into whatever window happens to be active.

**Screenshots**

![image](https://user-images.githubusercontent.com/31365175/202842252-40ea48bb-8e79-4f09-b318-b73a4bd07364.png)
When I click this, the command `sudo rm -rf /` will be pasted into my VS Code terminal (the window below that clipboard entry), rather than the GitHub issues page which was the window I intend to paste into. 

Obviously, don't actually try with that command, but this is just to highlight the potential damage this could do to systems.

**To Reproduce**
- GNOME Shell version: 42
- Distro: Fedora 36
- Windowing session: Wayland
- Steps to reproduce, if applicable:
1. Set window focus rules in Gnome tweaks to "Focus on hover" 
![image](https://user-images.githubusercontent.com/31365175/202842418-2772c5fc-a10a-4ab1-adf8-d7754cb0d09b.png)
3. Open two windows in split-screen
4. With the right window active, open Pano
5. Attempt to paste content that is on the far left of Pano's display
6. Observe content getting pasted to the wrong window

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:

This is literally over a million lines long, and is >40 MB. If it's absolutely necessary, I'll upload it but otherwise I'd rather not.

**Comment by oae** [comment]
You can use arrow keys to navigate between items. Pressing enter on an item will copy that. So you don't need to move the mouse. But if you want to use it with the mouse, maybe consider disabling the `Paste on Select` option in settings.
