### ISSUE TITLE
Add option to edit saved text

### ISSUE THREAD

**Issue by MontyQI** [oae/gnome-shell-pano#126]
**Is your feature request related to a problem? Please describe.**
If you accidentally copy too much text, or you want to delete something from it, you can't do that and must paste it and then edit this text.
**Describe the solution you'd like**
When you open pano, and hover over copied text small edit icon appears. When you click it you can edit this entry and save it in its edited form.

**Describe alternatives you've considered**
None

**Additional context**
[In android 13 there is similar solution.](https://www.xda-developers.com/android-13-beta-1-clipboard-editor-overlay/)

**Comment by oae** [comment]
I am not planning to add content editing.

**Comment by iconoclasthero** [comment]
That is unfortunate because it would be extremely useful.  Can you at least reopen this issue to see how many other people are interested in it as well?  Maybe someone can fork?
