### ISSUE TITLE
Incompatible with PopShell

### ISSUE THREAD

**Issue by Akorian** [oae/gnome-shell-pano#127]
I am using Fedora 37. And when using this extension with the PopShell extension, the menu to see and select stuff from the clipboard doesn't show up when clicking the icon. The problem is, that there is no way of adding the pano menu to the exceptions list in PopShell.  This is due to the pano menu not staying active when clicking away.

I would expect that the menu with the clipboard stuff shows up when I click the icon.

# To reproduce
- GNOME Shell version: 43
- Distro: Fedora 37
- Steps to reproduce, if applicable:
1. Install PopShell
2. Try to open the Pano menu by clicking the icon

This doesn't produce log data.

**Comment by BarbzYHOOL** [comment]
it works on pop os though

**Comment by jawadalkassim** [comment]
Same Issue on Pop OS with PopShell is on

**Comment by devalexwhite** [comment]
Running into this as well, specifically Pano doesn't appear if "Tile Windows" is on with Pop!_OS. Works fine when you turn off tile windows.

**Comment by oae** [comment]
PopShell breaks this extension. See https://github.com/pop-os/shell/issues/1534
