### ISSUE TITLE
Feasibility of migration to Deno for dependencies

### ISSUE THREAD

**Issue by 154pinkchairs** [oae/gnome-shell-pano#128]
**Is your feature request related to a problem? Please describe.**
The extensions relies on yarn and the imports are pulled from npm registry. This poses security risks.

**Describe the solution you'd like**
Make the imports to Deno compatible. Might work on that.

**Describe alternatives you've considered**
none possible

**Comment by 154pinkchairs** [comment]
See [this repo](https://github.com/ahgilak/deno_gi) for example

**Comment by oae** [comment]
Thank you for the feedback but i don't plan to use it.
