### ISSUE TITLE
An Object is alredy exported for the interface io.elhan.Pano at /io/elhan/Pano

### ISSUE THREAD

**Issue by dipeshsingh253** [oae/gnome-shell-pano#130]
**Describe the bug**
I tried to install Pano on my new pop os installation, when I installed it first it was not repsonding properly neither on key binding nor on clicking on icon in the panel.
I removed it and installed it again then I was getting this error.

An Object is alredy exported for the interface io.elhan.Pano at /io/elhan/Pano

**Expected behavior**
It should work propely and respond to the call via keybindings or clicks, it is not even visible on pressing keybindings

**Screenshots**
![Screenshot from 2022-12-29 13-23-42](https://user-images.githubusercontent.com/84814627/209921366-10d3b600-1e69-40db-ac45-fdc2a8fcd86e.png)

**Comment by oae** [comment]
This problem shouldn't occur now
