### ISSUE TITLE
I cannot paste in the gnome terminal

### ISSUE THREAD

**Issue by varadinov** [oae/gnome-shell-pano#134]
**Describe the bug**
I copy the text and then I try to copy the text in the gnome terminal. The paste is not working. 

**Expected behavior**
Pasting is working in gnome terminal

**Screenshots**
No need of screnshots

**To Reproduce**
- GNOME Shell version: 42.5
- Distro: Ubuntu 22.04
- Steps to reproduce, if applicable:
1. Copy text with ctrl+c 
2. Paste text with shift+super+v

The copy paste is working with other apps e.g. Browser, gtext and etc.

**Comment by oae** [comment]
Try holding the `shift` key when selecting an item from pano
