### ISSUE TITLE
Please add the ability to pin a clipped item

### ISSUE THREAD

**Issue by RabidAnubis** [oae/gnome-shell-pano#136]
This is a feature available in several other gnome clipboard extensions and would be perfect in Pano!

If there was a pin icon right beside the x (close) icon when you pull up the Pano clipped items that would be great.

The alternative or workaround I'm using right now is running Pano and another clipboard manager that supports pinning clips. I'd rather just run Pano.

**Additional context**

**Comment by gaussandhisgun** [comment]
yeah, it seems like literally every other clipboard manager can do pins, i dont get why it isn't a thing in pano yet, especially considering pano is like *the* best looking one out there

**Comment by oae** [comment]
Now you pin items with `ctrl` + `s` or using :star: icon and switch between all items/favorites with `alt` key
![image](https://user-images.githubusercontent.com/1043714/222009351-0d20452b-ebfe-419e-936c-b49a2f8d92fa.png)

**Comment by RabidAnubis** [comment]
Many thanks @oae ! Perfect!!
