### ISSUE TITLE
Copied to clipboard notification

### ISSUE THREAD

**Issue by sandenbergmelo** [oae/gnome-shell-pano#142]
It would be nice if it had the option to show a notification when something is copied to clipboard.
Like **[Clipboard indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/)** has:
![image](https://user-images.githubusercontent.com/77549672/220699135-48735daa-c6d2-4731-bed1-5ed396f97539.png)

**Comment by oae** [comment]
New version will include notifications.

![image](https://user-images.githubusercontent.com/1043714/222034780-f0faaac1-97c0-42b2-86b1-3f0297bcab75.png)
