### ISSUE TITLE
Feature Request: Add switch to return old icons (before March 2023 update). New icons aren't good looking.

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [oae/gnome-shell-pano#148]
**Is your feature request related to a problem? Please describe.**
I find new icons of content types look bad. 
![image](https://user-images.githubusercontent.com/45625440/223068307-350c9610-e2b8-4691-b71b-48d47e17ef88.png)
The strokes are too bold and the size is also bigger.

**Describe the solution you'd like**
In perfect I want to return old icons. But it can be my subjective opinion. So, add, please, a switch in settings to use system icons.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No context.

**Comment by yukina3230** [comment]
If users have custom icon pack on their system, the new icons look a bit out of place. So add a switch in settings to use system icons sounds good.
Please consider. Thank you.

**Comment by oae** [comment]
Old icons were not system icons either. I would like to hear @daudix-UFO's opinion on this

**Comment by daudix-UFO** [comment]
Also, maybe making them smaller (32px) will make them look better?

**Comment by muhammadyusuf-kurbonov** [comment]
And why color is so "brown"? Previous color were better
