### ISSUE TITLE
feature: Add clear clipboard history button

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [oae/gnome-shell-pano#15]
**Is your feature request related to a problem? Please describe.**
I have increased the history size to 20. After work, I don't want to see these texts anymore :smiley: and wanna clear the whole history. But I couldn't find the button `Clear clipboard history`. There is solution to remove each item, but it is less comfortable

**Describe the solution you'd like**
Add button `Clear` on the right top for panoWindow
![image](https://user-images.githubusercontent.com/45625440/187038298-e5bf8d0b-c357-4157-bd4b-826ee2ccaebc.png)

**Describe alternatives you've considered**
Manually remove each item - too much work.

**Additional context**
Great and awesome project. And perfect code (I'm a developer too :+1: ). Good luck :star: * Infinity

**Comment by oae** [comment]
Hi, it already has this functionality. You can clear all history by going to the Pano extension settings.

![image](https://user-images.githubusercontent.com/1043714/187188610-1fd8bf6f-e97c-4ac5-86cf-eacd5ab73364.png)

**Comment by muhammadyusuf-kurbonov** [comment]
Thank you very much and good luck!
