### ISSUE TITLE
Display Link text when no preview available

### ISSUE THREAD

**Issue by A-nglea** [oae/gnome-shell-pano#151]
This update destroys a valuable feature. If links only produce json or xml responses, a generic link graphic is shown. Thus there is no way to distinguish one link from another. Please revert to the old defaults of showing the start of the link text if no preview is available. Sometimes less is more;  I liked Pano before the update better.

**Comment by A-nglea** [comment]
example:

https://manifest.prod.boltdns.net/license/v1/cenc/widevine/1242911124001/9cb0b361-6f80-4ac6-bd9e-022587dd9e87/669193bf-76e4-4ce9-af16-724d2f8bfc96?fastly_token=NjQyMzY1YjRfNTNlZDFjMTEyMTBiNzg5Y2QwNmFjODhhMGFmNTY1MmY2MDNlZTBmOGE4MDk1YTAwNmZlYTU0OTQ3MDA0Nzg1NA%3D%3D

https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/1242911124001/9cb0b361-6f80-4ac6-bd9e-022587dd9e87/6s/manifest.mpd?fastly_token=NjQyYWZlMDZfZjFiNjgzNWM3NThkMGI5YmFkYTIyZDU0MTA3OTc3MDYyZGIzMDRkNjZlMzM4YWNhYzdiMTgwNWY2YmYyYjViYQ%3D%3D

Give incognito responses.

**Comment by oae** [comment]
This shows the start of the link when I copy it.

![image](https://user-images.githubusercontent.com/1043714/223168889-b955b7b6-b2ac-42d0-be4f-35fce125f987.png)

**Comment by A-nglea** [comment]
I don't see the lower black band with white text.  I only see the arrow/World on a white background
![Screenshot from 2023-03-06 16-27-00](https://user-images.githubusercontent.com/55594811/223170989-d71ad780-01f6-4493-ad13-5c4ce4a2277e.png)

**Comment by oae** [comment]
Can you try disabling all extensions and check it again? Also what is the output of the `dconf dump /org/gnome/shell/extensions/pano/`? Do you use custom CSS for your shell?

**Comment by oae** [comment]
Als do you use upscaling in display settings?

**Comment by A-nglea** [comment]
Displaying alll extension except pano but having recycled Pano gave no change.
dconf:
dconf dump /org/gnome/shell/extensions/pano/
[/]
history-length=40
incognito-shortcut=['<Shift><Control>n']
is-in-incognito=false
link-previews=true
open-links-in-browser=false
paste-on-select=false
play-audio-on-copy=true
send-notification-on-copy=true
show-indicator=true
sync-primary=true
window-background-color='rgb(0,0,0)'
window-height=480

[link-item]
header-color='rgb(0,0,0)'
metadata-description-color='rgb(0,0,0)'
metadata-description-font-family='DejaVu Sans'
metadata-description-font-size=12
metadata-link-color='rgb(224,27,36)'
metadata-link-font-family='DejaVu Sans'
metadata-link-font-size=10
metadata-title-font-family='DejaVu Sans'
metadata-title-font-size=13

[text-item]
body-bg-color='rgb(248,228,92)'

**Comment by oae** [comment]
I am able to reproduce this issue. This occurs when a different scale is being used. Thank you for the report. I will try to fix it.
