### ISSUE TITLE
Panel doesn't fit on the screen

### ISSUE THREAD

**Issue by flexagoon** [oae/gnome-shell-pano#152]
## Description

The panel doesn't fully fit on the screen

### Problem Explanation

No matter what the height of the panel is, it gets cut off at the bottom

### Expected Behavior

The panel should fully fit

### Steps To Reproduce

1. Open the panel

#### It happens with any application?

- [x] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

### Environment

- GNOME Shell version: 43.3
- Distro: Fedora
- Distro version: 37

### Screenshots

![image](https://user-images.githubusercontent.com/66178592/223178941-bb5373cf-721c-4987-8340-9875de3c30e5.png)
![image](https://user-images.githubusercontent.com/66178592/223179089-0e93d18e-dafe-4305-a801-434528cb9454.png)

#### Screenshot 1 description

How it looks with the default window size

#### Screenshot 2 description

How it looks with window size = 1000

#### Gnome

No output

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
...
[/]
is-in-incognito=false
sync-primary=false
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
...
['gsconnect@andyholmes.github.io',
'appindicatorsupport@rgcjonas.gmail.com',
'AlphabeticalAppGrid@stuarthayhurst',
'date-menu-formatter@marcinjakubowski.github.com',
'CoverflowAltTab@palatis.blogspot.com',
'activitywatch_gnome@flexagoon.com',
'focused-window-dbus@flexagoon.com',
'pano@elhan.io',
'blur-my-shell@aunetx',
'rounded-window-corners@yilozt',
'noannoyance@daase.net']

```

**Comment by oae** [comment]
Should be fixed with the latest commit.
