### ISSUE TITLE
Feature request: return old look

### ISSUE THREAD

**Issue by Milk-Cool** [oae/gnome-shell-pano#158]
**Is your feature request related to a problem? Please describe.**
I think some people might not like the new look of Pano so there should be an option to return the old style

**Describe the solution you'd like**
There should be a switch in the extension settings that allows you to enable the old look

**Describe alternatives you've considered**
Changing the colors, however it does not fix the spacing

**Comment by oae** [comment]
I have added many customizations to Pano. You can reproduce the old look if you want.
