### ISSUE TITLE
possible copy'n'paste error from gnome-shell-extensions-sync

### ISSUE THREAD

**Issue by doppelhelix** [oae/gnome-shell-pano#16]
**Describe the bug**
The .xml in the schemas folder is called `org.gnome.shell.extensions.extensions-sync.gschema.xml`

**Expected behavior**
This file should probably be called `org.gnome.shell.extensions.pano.gschema.xml`

**Comment by oae** [comment]
Oh. Thank you. I copied the resources from my other extension :smile:
