### ISSUE TITLE
Incompatibility with pop shell tiling

### ISSUE THREAD

**Issue by caetano-m** [oae/gnome-shell-pano#162]
## Description

**What is the bug?**

When the pop shell tiling is activated, the Pano window won't show, either by clicking on the icon on the topbar or using the keyboard shortcut.

### Problem Explanation

The bug happens when you activate the tiling of the pop shell extension. I have not tested with other tiling extensions such as Forge.

### Expected Behavior

The Pano window should appear despite the tiling being activated or not.

### Steps To Reproduce

Steps to reproduce:

1. Have both Pano and the Pop Shell extension installed
2. Activate the tiling mode from the Pop Shell extension
3. Try to activate Pano with either Shift + Super + V or the top bar icon
4. Pano window won't be visible

#### It happens only on one computer?

- [x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific extension installed?

The bug is specifically about extension incompatibility

### Environment

- GNOME Shell version: 42.5
- Distro: Pop!_OS
- Distro version: 22.04 LTS
- Observation: I have not tested this under the COSMIC Shell, this was tested under gnome-shell installed via the `gnome-session` package

**Comment by oae** [comment]
PopShell breaks this extension. See https://github.com/pop-os/shell/issues/1534
