### ISSUE TITLE
Vertical orientation

### ISSUE THREAD

**Issue by durka** [oae/gnome-shell-pano#165]
Just an idea. I don't know, to me it's just more intuitive to view history in a vertical scroll instead of horizontal scroll. Is it feasible to add an option to swap the orientation of the gallery?

I realize that most screens are wide, so you definitely wouldn't be able to see as many entries, unless they get squashed into a rectangular instead of square shape.

**Comment by oae** [comment]
It is in the works :)

**Comment by durka** [comment]
Awesome!

**Comment by oae** [comment]
I have added position settings. For now, they will be square but after I implement compact mode(See https://github.com/oae/gnome-shell-pano/issues/150), this can be more useful I think.
![image](https://user-images.githubusercontent.com/1043714/224566038-638170b3-c1ac-4c81-8344-50c751b9b2e3.png)
