### ISSUE TITLE
Pano copies the same link multiple times

### ISSUE THREAD

**Issue by shasherazi** [oae/gnome-shell-pano#17]
**Describe the bug**
Pano creates multiple copies of the same link on copying the same link multiple times.

**Expected behavior**
If the link is already the most recently copied item it shouldn't add the same item to the clipboard again.

**Screenshots**
![image](https://user-images.githubusercontent.com/63230301/187067204-244f5d77-80c1-4a73-8070-82c427ecb888.png)

**To Reproduce**
- GNOME Shell version: 42.4
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Copy a link
2. Copy that link again
3. And again...
4. Bug

**Log data**
Output from `journalctl /usr/bin/gnome-shell`: [Quite long text, only showing last 1000 lines](https://hastebin.com/rotakasuhu.apache)

**Comment by oae** [comment]
It seems like you have the clipboard indicator extension installed also. Can you try disabling it and check if the problem continues?

**Comment by shasherazi** [comment]
Yep, disabling the clipboard indicator extension solved the problem. Can you tell me why this happened tho?

**Comment by oae** [comment]
I am not sure why this is this happening. I will try to reproduce it.
