### ISSUE TITLE
Two blocks are highlighted when a mouse hovers over a block - not enough contrast

### ISSUE THREAD

**Issue by marcinjahn** [oae/gnome-shell-pano#18]
**Describe the bug**
A mouse hovering over a block highlights it. If I press arrow keys to select a different block, I may end up with two blocks being highlighted. It creates confusion, I am no longer sure which block is selected when I press ENTER.

If I open Pano and it happens that my mouse cursor is over some Pano block/item, it gets highlighted automatically.

**Expected behavior**
If I open the Pano panel, the mouse position over some block should not highlight it automatically.
Only one block should be highlighted at a time. The highlighted block should get selected when I press ENTER.

**Screenshots**
![image](https://user-images.githubusercontent.com/10273406/187073220-8914533d-db4c-4f2d-8333-fa5c4d0d8940.png)

**To Reproduce**
- GNOME Shell version: 42
- Distro: Fedora 36
- Steps to reproduce, if applicable:
Provided

**Comment by marcinjahn** [comment]
Wait, just after submitting, I realized that the selection caused by the mouse hover is actually different than the selection caused by arrow keys. I think this issue is linked to #12. The selection and hover should be more distinct.

**Comment by oae** [comment]
Thank you for the report. I will change it. You can track the issue in #12
