### ISSUE TITLE
Can't install on Ubuntu 20.04.6 : SyntaxError: expected expression, got '.' @ pano@elhan.io/extension.js:111

### ISSUE THREAD

**Issue by Johann-Tree** [oae/gnome-shell-pano#186]
## Description
Error while trying to install Pano on Ubuntu 20.04.6 with GNOME 3.36.8

### Problem Explanation
Installing fails, I see following error messages in /var/log/syslog:
```
JS WARNING: [/home/user/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js 65]: test for equality (==) mistyped as assignment (=)?
JS ERROR: Extension pano@elhan.io: SyntaxError: expected expression, got '.' @ /home/user/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:111
```

### Expected Behavior

- Pano should install without errors.

### Environment

- GNOME Shell version: 3.36.8
- Distro:  Ubuntu
- Distro version: 20.04.6 LTS

**Comment by oae** [comment]
Pano only supports Gnome shell version 42+. I am not planning to add support for older versions.
