### ISSUE TITLE
feature: Mark pastes as "favorites"

### ISSUE THREAD

**Issue by ravila4** [oae/gnome-shell-pano#19]
Perhaps it would be a useful feature to "star" or otherwise mark some pastes as favorites to prevent them from being deleted from history.

**Comment by oae** [comment]
Thank you for the suggestion. This is on my backlog. I will implement it in future releases.

**Comment by oae** [comment]
Now you pin items with `ctrl` + `s` or using :star: icon and switch between all items/favorites with `alt` key
![image](https://user-images.githubusercontent.com/1043714/222009351-0d20452b-ebfe-419e-936c-b49a2f8d92fa.png)
