### ISSUE TITLE
Requiring Gda, version none: Typelib file for namespace 'Gda' (any version) not found

### ISSUE THREAD

**Issue by Uptaker** [oae/gnome-shell-pano#192]
## Description

**What is the bug?**

Pano crashes with the following error on install:

```
Requiring Gda, version none: Typelib file for namespace 'Gda' (any version) not found
```

I don't know how to resolve this. Googling about 'Gda' leads to anything else other than this exact bug :(. I must be missing some sort of dependency, but I can't figure out what exactly.

I can use the settings, but enabling the extension crashes it with the same error. Disabling all other extensions did not affect it.

Write a clear and concise description of what the bug is:

The bug happens when ...

I try to Install Pano on a fresh install of Fedora 38

A clear and concise description of what you expected to happen, and how the actual outcome differs:

- Pano shouldn't crashed with `Requiring Gda, version none: Typelib file for namespace 'Gda' (any version) not found`
- It should behave ...

## Reprodution

**How one can find the bug?**

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Open application ...
2. **crash**

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [x ] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [ x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [ x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [x ] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

- GNOME Shell version: 44.1
- Distro: Fedora
- Distro version: 38

### Screenshots

If applicable, add screenshots to help explain your problem:

The error in question

![image](https://user-images.githubusercontent.com/16374628/236941703-38b31c66-8558-44e0-bebe-3a1a22b6be26.png)

#### What is pasted, if applicable

``` text
...
```

#### Application Version

``` bash
$ app --version  # ...
1.74.3
```

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
...
```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
(empty)
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
['appindicatorsupport@rgcjonas.gmail.com',
'noannoyance@daase.net',
'background-logo@fedorahosted.org',
'transparent-top-bar@ftpix.com',
'gsconnect@andyholmes.github.io',
'freon@UshakovVasilii_Github.yahoo.com',
'pano@elhan.io',
'advanced-alt-tab@G-dH.github.com',
'aztaskbar@aztaskbar.gitlab.com',
'blur-my-shell@aunetx',
'caffeine@patapon.info',
'custom-hot-corners-extended@G-dH.github.com',
'grand-theft-focus@zalckos.github.com',
'Hide_Activities@shay.shayel.org',
'runcat@kolesnikov.se',
'Vitals@CoreCoding.com',
'weatheroclock@CleoMenezesJr.github.io']
```

**Comment by Uptaker** [comment]
I'm a dummy dum dum who doesn't search old issues to resolve this *sigh*

https://github.com/oae/gnome-shell-pano/issues/139

**Comment by smileBeda** [comment]
Unfortunately even following steps and installing libgda 6+ and gsound, I still get this error, on gnome 45 using X

**Comment by smileBeda** [comment]
Nevermind: had to logout/in
I wonder how many apps I already ditched as "not working" just because I did not do that.

Anyway, _this_ app was so important I tried haha.

Great job replicating PasteApp ;)
