### ISSUE TITLE
Search after navigating with arrows

### ISSUE THREAD

**Issue by forteller** [oae/gnome-shell-pano#199]
Not sure if this is a bug or a feature request, but if you start out thinking you can easily navigate to the thing you want to paste with arrows, and then notice that it wasn't "right there" after all and start typing to search instead, nothing happens. You have to close and reopen Pano, or press Shift+Tab, to be able to start searching. I'd love it to have "type to search" in Pano, also after starting navigation.

Thanks a lot for this great tool!

**Comment by Totto16** [comment]
@forteller Not sure if it was a Gnome / GJS bug, but with Gnome 45 on my Ubuntu 23.10 machine, it works. You can type after navigating with the arrow keys, and then you search. 

Can you test on your machine again and if it still doesn't work, could you tell us the exact version of your shell and OS. If it's a gnome  / GSJ bug and you use gnome < 45, we can't do anything against it 😓

**Comment by forteller** [comment]
Yeah, now it works. Well, thanks :)
