### ISSUE TITLE
Code preview doesn't use monospace font

### ISSUE THREAD

**Issue by Roy-Ermers** [oae/gnome-shell-pano#20]
**Describe the bug**
When you copy a piece of code, the preview shown in pano doesn't use a monospace font.

**Expected behavior**
A monospace font is used on the code preview

**Screenshots**
![image](https://user-images.githubusercontent.com/8841123/187160480-c4ea3301-f5a4-4590-a134-e99dc76e693e.png)

font settings 
![image](https://user-images.githubusercontent.com/8841123/187160797-646ea060-c786-4618-aa01-1468773c4d87.png)

**To Reproduce**
- GNOME Shell version: 42
- Distro: Fedora 36

**Comment by oae** [comment]
Thank you for the report. I will fix it in the next version
