### ISSUE TITLE
Installing on VanillaOS: libgda/gsound not detected after install

### ISSUE THREAD

**Issue by TDuffinNTU** [oae/gnome-shell-pano#201]
## Description

Bit of a niche one, but tried installing on vanillaOS and couldn't get the extension to detect the dependencies even though they're present on the APX package manager.

### Problem Explanation

As above.

The bug happens when ...

### Expected Behavior

A clear and concise description of what you expected to happen, and how the actual outcome differs:

- Pano shouldn't ...
- It should behave ...

## Reprodution

Attempting to install pano via the gnome extensions app on a fresh install of vanilla OS, after installing the dependencies via APX.

### Steps To Reproduce

1. Install VanillaOS
2. Install pano deps (gsound and libgda)
3. install pano via gnome extension manager
4. pano will fail to load, saying the deps arent present.

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [x] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

- GNOME Shell version: 43.1
- Distro: VanillaOS
- Distro version: 22.10 all

### Screenshots
![image](https://github.com/oae/gnome-shell-pano/assets/43959652/e4918b08-9f4d-49dc-a523-5b21bf671439)
![image](https://github.com/oae/gnome-shell-pano/assets/43959652/99f98df8-650e-454b-8e29-f948a1677c7a)

#### Screenshot 1 description

Evidence of gsound and libgda installed.

#### Screenshot 2 description

Pano error

**Comment by sskartheekadivi** [comment]
I'm facing the same on Ubuntu 22.04.02 LTS. 
Tried removing and reinstalling the extension but didn't work.

**Comment by busybox11** [comment]
@TDuffinNTU You'd have to install the required binaries on the host system, this could probably work by installing them to the ABRoot shell. I don't have experience with Vanilla OS myself, only some knowledge about it, so I can't really help with that - yet. Just know that apx won't do anything here since it will install the packages in a container - they need to be in the same host as GNOME, the host OS itself.

@sskartheekadivi You shouldn't have any issues though, as long as you have the necessary packages installed.

**Comment by TDuffinNTU** [comment]
Yup I think this might just be a limitation of Vanilla's container system for now. Dependency hell strikes again!

**Comment by zvictor** [comment]
Never mind, I managed to fix it!
https://github.com/oae/gnome-shell-pano/issues/271#issuecomment-2433493405

**Comment by vleeuwenmenno** [comment]
@zvictor You said you managed to fix it, did this work for you for alpha3 as well? I am running NixOS 24.05 and tried your patch from #271 but I had no luck getting past the GSound issues.
