### ISSUE TITLE
Any possibility to enable Gnome 40 compatibility?

### ISSUE THREAD

**Issue by logicito** [oae/gnome-shell-pano#206]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Commenter25** [comment]
This could safely be closed at this point, right?

**Comment by Totto16** [comment]
No, unfortunately not, we only ever will support gnome 42 > and nowadays, I am sure, that a 2 year old gnome will be available everywhere
