### ISSUE TITLE
Duplicated entries (links/urls)

### ISSUE THREAD

**Issue by VandrerenErik** [oae/gnome-shell-pano#21]
If the entry already exist and it is copied again just move it to the top (left in this case) instead of duplicating it. This seems to only happen with links/urls.

![image](https://user-images.githubusercontent.com/54407345/187200608-69dc348f-9d63-4f2e-bd29-e2cb1643f2c1.png)

**Comment by oae** [comment]
Do you have another clipboard extension installed? It may be a similar problem to #17

**Comment by VandrerenErik** [comment]
No, I deleted the previous one (clipboard indicator) after I found this wonderful replacement. And yes, it is fully deleted from the system, as a matter of fact this is a fresh installed, pano is the only one ever installed.

**Comment by oae** [comment]
can you check if any logs are printed related to this using `journalctl /usr/bin/gnome-shell` command?

**Comment by VandrerenErik** [comment]
Here you go, 8.6mb of logs. The link will expire after one day or 20 downloads.

https://send.vis.ee/download/572af4461972f2a2/#b094pdszyjiA5yyFt_4ohA

**Comment by VandrerenErik** [comment]
I'm checking if extensions sync dragged configs from my old install and other things.

**Comment by VandrerenErik** [comment]
I can see "Clipboard history" in the logs, even though I removed that extension ages ago.

**Comment by VandrerenErik** [comment]
Maybe KDE Connect (GSConenct)? it has a clipboard syncronization that could be affecting pano somehow.

**Comment by VandrerenErik** [comment]
> Maybe KDE Connect (GSConenct)? it has a clipboard syncronization that could be affecting pano somehow.

I just checked and KDE Connect does not seem to affect Pano in anyway

**Comment by VandrerenErik** [comment]
Couldn't this just bad regex processing due to the slash?

**Comment by JoseBritto** [comment]
I had this same issue yesterday but for some reason can't reproduce it now. I have no idea what fixed it.

Extensions I have enabled if that matters:
![image](https://user-images.githubusercontent.com/64070234/188695369-dd33746f-0824-46f6-8d96-ba37833f741d.png)

**Comment by oae** [comment]
I think I fixed it. When fetching the link content, if you copy the URL again, it would result in duplicate entries.
