### ISSUE TITLE
[Feature Request] Add GNOME 45 Support

### ISSUE THREAD

**Issue by git-Hmmm** [oae/gnome-shell-pano#210]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by Koitharu** [comment]
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by ChrisLauinger77** [comment]
Looks like this is not an easy task:
https://discourse.gnome.org/t/migrating-exteions-to-gnome45-in-typescript/17313

**Comment by yusufbarisk** [comment]
any updates?

**Comment by c3101** [comment]
i wasn't looking at my arch update this morning, updated gnome to 45, pano dead, i want to cry!

**Comment by ChrisLauinger77** [comment]
There is also this:
https://github.com/Keruspe/GPaste
debian has packages for it. I switched to pano from that one - now I switched back :(

**Comment by mbeps** [comment]
I assume getting this extension to work with Gnome 45 would be a bit more difficult as it uses TypeScript instead of regular JavaScript.
