### ISSUE TITLE
Option to change position on screen

### ISSUE THREAD

**Issue by in4matix** [oae/gnome-shell-pano#224]
I use Dash2Panel on Ubuntu 22.04.3 and it will make a lot more sense to have Pano appear at the top of the screen (or perhaps even the sides).

**Comment by oae** [comment]
You can not select the window position

![image](https://github.com/oae/gnome-shell-pano/assets/1043714/1e02353d-278f-4a21-819c-addedaad4382)

**Comment by in4matix** [comment]
Thank you very much!
