### ISSUE TITLE
Not updated version on Gnome Extensions website.

### ISSUE THREAD

**Issue by PesTospertnyj** [oae/gnome-shell-pano#231]
## Description
Extension version is not updated at [Gnome Extensions](https://extensions.gnome.org/extension/5278/pano/)
**What is the bug?**
Extension appears like incompatible with Gnome shell 45.1 (Fedora 39)

![изображение](https://github.com/oae/gnome-shell-pano/assets/43485813/1b851f09-5181-4bf5-996d-e0d01d5910fd)
![изображение](https://github.com/oae/gnome-shell-pano/assets/43485813/dfcfd88e-9518-4d74-ba00-76b9c4413056)

**Comment by oae** [comment]
See https://github.com/oae/gnome-shell-pano/issues/230#issuecomment-1802157359
