### ISSUE TITLE
Auto-pastes in Gnome Shell overview search field directly on log in

### ISSUE THREAD

**Issue by thyttan** [oae/gnome-shell-pano#232]
### Problem Explanation

The bug happens when I log in to my system. The top clipboard entry will be automatically entered into the gnome shell overview search field.

It happens only if 'Paste on Select' setting is toggled on. If it is toggled off the bug does not occur.

### Expected Behavior

A clear and concise description of what you expected to happen, and how the actual outcome differs:

- Pano shouldn't paste automatically without the user telling it to.

## Reprodution

**How one can find the bug?**

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Have 'Paste on Select' setting toggle on.
2. Log in from having been logged out.
3. BUG: The top clipboard entry is automatically entered in gnome shell overview search field
4. See the bug happening in the ...

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [ ] Yes, it applies to any application.
- [x] No. Only with the following applications:
  - Gnome shell overview directly after log in.
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

- GNOME Shell version: 45.1
- Distro: Fedora Linux
- Distro version: 39

- Pano version: v20

### Screenshots

![Screenshot from 2023-11-09 02-08-47](https://github.com/oae/gnome-shell-pano/assets/97237430/26046ade-fb60-4497-9088-d8d43af3cd07)

#### Screenshot 1 description

Overview directly after log on.

#### What is pasted, if applicable

The contents of the top entry on the clipboard.

#### Application Version

``` bash
$ gnome-shell --version
GNOME Shell 45.1
```

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
...
```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
[/]
global-shortcut=['<Control><Alt>v']
keep-search-entry=false
link-previews=false
open-links-in-browser=false
paste-on-select=true
play-audio-on-copy=true
watch-exclusion-list=true
wiggle-indicator=true
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
['background-logo@fedorahosted.org',
'gsconnect@andyholmes.github.io',
'emoji-selector@maestroschan.fr',
'ideapad-controls@azzamalsharafi.gmail.com',
'display-scale-switcher@knokelmaat.gitlab.com',
'pip-on-top@rafostar.github.com',
'forge@jmmaranan.com',
'github-actions@arononak.github.io',
'screen-rotate@shyzus.github.io',
'pano@elhan.io',
'BingWallpaper@ineffable-gmail.com',
'caffeine@patapon.info',
'gestureImprovements@gestures',
'gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com',
'just-perfection-desktop@just-perfection',
'quick-touchpad-toggle@kramo.hu',
'reorder-workspaces@jer.dev',
'top-bar-organizer@julian.gse.jsts.xyz',
'unite@hardpixel.eu',
'vim-altTab@kokong.info']
```
(I also get the bug if I disable all other 'Manually installed' extensions apart from Pano)

**Comment by thyttan** [comment]
Just noticed this is also mentioned here: https://github.com/oae/gnome-shell-pano/pull/222#issuecomment-1793323824

**Comment by Pkcarreno** [comment]
It not only happened in gnome search bar, if I have an app with input in the current window then it pastes the last content copied in that app, for example: the terminal

btw, it is not necessary to log out, when suspend happens too.

**Comment by KoljaFrahm** [comment]
I can confirm this issue

**Comment by salloom-domani** [comment]
same here

**Comment by spiftire** [comment]
Happens to me as well

**Comment by ahming9486** [comment]
Have same issue here, will auto paste after unlocking from lock screen.
Ubuntu 23.10 with Gnome Shell 45.0

**Comment by LeGmask** [comment]
I've the same issue
![image](https://github.com/oae/gnome-shell-pano/assets/53308142/25316543-2381-4b28-bfd8-adfae6fa4f22)
