### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by manur0** [oae/gnome-shell-pano#234]
## Description

Install from "https://extensions.gnome.org/extension/5278/pano/" fails

### Problem Explanation

I go to the page https://extensions.gnome.org/extension/5278/pano/ and I click on "ON" from chromium (Chromium: 117.0.5938.140, Official Build, 64-bit) or firefox (119.0, 64-bit) browsers.
I use Ubuntu 20.04.6 LTS with gnome (3.36.8).

### Details
[
The settings of extension pano@elhan.io had an error:
```
SyntaxError: expected expression, got '.'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
]

#### It happens with any application?

- [ x] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [x ] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [ ] I don't think that the configuration matters.
- [ x] Yes. Only if the following config is set up: 
  - gnome (3.36.8)

#### It happens only with some specific extension installed?

- [ x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

### Environment

- GNOME Shell version: 3.36.8
- Distro: Ubuntu
- Distro version: 20.04.6 LTS

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
-- Logs begin at Fri 2022-09-30 07:17:55 CEST. --
nov. 13 12:23:48 reynier-latitude-5520 gnome-shell[6243]: JS WARNING: [/home/reynier/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js 65]: test for equality (==) mistyped as assignment (=)?
nov. 13 12:23:48 reynier-latitude-5520 gnome-shell[6243]: JS ERROR: Extension pano@elhan.io: SyntaxError: expected expression, got '.' @ /home/reynier/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:111

```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
['pano@elhan.io']
```

**Comment by RoboticsChen** [comment]
I encountered the same problem

**Comment by oae** [comment]
only Gnome Shell version 42 and up is supported. See https://github.com/oae/gnome-shell-pano?tab=readme-ov-file#supported-shell-versions
