### ISSUE TITLE
The last copied value is automatically pasted every time I login

### ISSUE THREAD

**Issue by everyx** [oae/gnome-shell-pano#244]
## Description

The last copied value is automatically pasted every time I log in

### Problem Explanation

The bug happens when I login, and the copied value is automatically pasted, when I disable pano, everything returns to normal.

### Expected Behavior

Nothing pasted

### Steps To Reproduce

1. Open gedit
2. Input some text and copy it
3. Logout and login again
4. the gedit text will automatic append the text your copied before.

#### It happens with any application?

- [x] Yes, it applies to any application.

#### It happens only on one computer?

- [x] I don't know.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

- GNOME Shell version: 45.1
- Distro: Arch Linux
- Distro version: rolling

### Screenshots

https://github.com/oae/gnome-shell-pano/assets/1665522/ee460f89-9c8f-489b-a96a-c3bf6b08826b

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
Nov 25 14:41:59 Arch gnome-shell[1788]: ../glib/gobject/gsignal.c:2777: instance '0x561994d3a230' has no handler with id '499269'
Nov 25 14:41:59 Arch gnome-shell[1788]: [pano] [extension] extension is disabled
Nov 25 14:42:05 Arch gnome-shell[1788]: meta_dbus_session_manager_uninhibit: assertion 'priv->inhibit_count > 0' failed
Nov 25 14:42:05 Arch gnome-shell[1788]: meta_dbus_session_manager_uninhibit: assertion 'priv->inhibit_count > 0' failed
Nov 25 14:42:05 Arch gnome-shell[1788]: meta_dbus_session_manager_uninhibit: assertion 'priv->inhibit_count > 0' failed
Nov 25 14:42:05 Arch gnome-shell[1788]: loading user theme: /home/everyx/.local/share/themes/Custom-Accent-Colors/gnome-shell/gnome-shell.css
Nov 25 14:42:05 Arch gnome-shell[1788]: [pano] [extension] extension is enabled
Nov 25 14:42:06 Arch gnome-shell[1788]: Received multiple virtual 0x1d key releases (ignoring)
```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
[/]
global-shortcut=['<Super>v']
history-length=20
is-in-incognito=false
paste-on-select=true
play-audio-on-copy=false
send-notification-on-copy=false
shortcut=['<Super>v']
show-indicator=false
sync-primary=false
watch-exclusion-list=true
wiggle-indicator=false
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
['timepp@zagortenay333',
'desktop-cube@schneegans.github.com',
'windowIsReady_Remover@nunofarruca@gmail.com',
'GPU_profile_selector@lorenzo9904.gmail.com',
'gnome-shell-screenshot@ttll.de',
'advanced-alt-tab@G-dH.github.com',
'trayIconsReloaded@selfmade.pl',
'BingWallpaper@ineffable-gmail.com',
'emoji-selector@maestroschan.fr',
'gsconnect@andyholmes.github.io',
'appindicatorsupport@rgcjonas.gmail.com',
'just-perfection-desktop@just-perfection',
'color-picker@tuberry',
'user-theme@gnome-shell-extensions.gcampax.github.com',
'drive-menu@gnome-shell-extensions.gcampax.github.com',
'autohide-battery@sitnik.ru',
'shuzhi@tuberry',
'ibus-tweaker@tuberry.github.com',
'noannoyance@daase.net',
'blur-my-shell@aunetx',
'gnome-compact-top-bar@metehan-arslan.github.io',
'transparent-top-bar@zhanghai.me',
'date-menu-formatter@marcinjakubowski.github.com',
'ibus-switcher@kevinhwang91.github.com',
'Battery-Health-Charging@maniacx.github.com',
'legacyschemeautoswitcher@joshimukul29.gmail.com',
'Hide_Activities@shay.shayel.org',
'bluetooth-quick-connect@bjarosze.gmail.com',
'custom-accent-colors@demiskp',
'auto-move-windows@gnome-shell-extensions.gcampax.github.com',
'cronomix@zagortenay333',
'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
'pomodoro@arun.codito.in',
'pano@elhan.io']
```

**Comment by shetozz** [comment]
I can confirm and add to that, it happens after restarts too, and pasts the last copied thing in gnome search.
System is Fedora 39 workstation, Gnome v45.1.

**Comment by shetozz** [comment]
And also I think this is a replica from #232

**Comment by MicaelJarniac** [comment]
> I can confirm. It seems that disabling the "Paste on Select" option this bug no longer occurs.

Thank you! I was also having this issue, and this fixed it for me. Not the best solution, but for now it should do the trick.

**Comment by aidanhadley** [comment]
can confirm, had this same issue, and disabling paste on select fixed the issue. endeavouros, gnome 45.

**Comment by aaronjamt** [comment]
Not sure why this was closed? I still have this issue and it appears the only "solution" here is "turn off that setting". Shouldn't this issue stay open until the underlying issue is solved?

**Comment by eldelacajita** [comment]
Maybe it was fixed by a commit, but not released yet?

**Comment by tdgroot** [comment]
Yeah looks like it was fixed on master, but the fix hasn't been released yet. So just use the workaround at least until next release
