### ISSUE TITLE
Pano copies storage folder contents into Wastebasket folder

### ISSUE THREAD

**Issue by neildarlow** [oae/gnome-shell-pano#25]
**Describe the bug**
When using Pano the GNOME Wastebasket icon in Nautilus indicates deleted content. Opening the Wastebasket folder shows duplicates of the Pano storage folder (from under .local/share) being there.

**Expected behavior**
Pano should not, as part of its operation, put content into the user's Wastebasket folder.

**Screenshots**
N/A.

**To Reproduce**
- GNOME Shell version: 42.4
- Distro: fedora 36 Silverblue
- Steps to reproduce, if applicable:
1. Use Pano
2. Examine contents of Wastebasket folder
4. Bug

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by oae** [comment]
This only occurs if you clear your history from the settings. When you clear history I trash all the cached files and the database.

**Comment by neildarlow** [comment]
That's fine but It shouldn't go into the Wastebasket. You could do that silently.

**Comment by oae** [comment]
Thank you for the feedback.
