### ISSUE TITLE
Pano Pastes Automatically on Login - GNOME 45

### ISSUE THREAD

**Issue by derevo** [oae/gnome-shell-pano#251]
## Description

Pano automatically pastes active clipboard item upon login

### Problem Explanation

When Pano is enabled on GNOME 45, whatever is currently on the clipboard is automatically pasted to whatever application is in focus immediately upon login.

This bug happens when Pano is enabled as a GNOME extension, and happens regardless of whether it is the only enabled extension or is active with other extensions. This bug happens upon _any_ login, including system start, unlocking session, etc. I have only reproduced with an account that requires a password to unlock.

**Update: This happens when the "Paste on Select" config is enabled.**

### Expected Behavior

Expected:
* Pano should not automatiucally paste from the clipboard upon login.
* Pano should only paste from the clipboard when the system keyboard shortcut is entered.

Actual:
* Pano automatically pastes from clipboard upon login

### Steps To Reproduce

1. Install Pano, as per standard instructions
2. Enable Pano as a GNOME extension
3. **Enable the "Paste on Select" configuration option**
4. Copy an item to the clipboard with Pano enabled
5. Focus an application with a text input
6. Focus the text input
7. Lock the current GNOME session with the relevant keyboard shortcut
8. Unlock the GNOME session with your password
9. See that your previous clipboard item has now been pasted into the text area of the application you focused in Steps 4 & 5

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [X] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [X] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [X] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [X] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

* GNOME 45.2
* Fedora 39
* Wayland Session

#### What is pasted, if applicable

The last item copied (current clipboard item)

#### Application Version

``` bash
$ app --version  # ...
1.74.3
```

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
Dec 18 09:46:20 fedora gnome-shell[5253]: ../gobject/gsignal.c:2777: instance '0x55d4c90ed3d0' has no handler with id '23398278'
Dec 18 09:46:20 fedora gnome-shell[5253]: [pano] [extension] extension is disabled
Dec 18 09:46:26 fedora gnome-shell[5253]: [pano] [extension] extension is enabled
Dec 18 09:46:27 fedora gnome-shell[5253]: Received multiple virtual 0x1d key releases (ignoring)
```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
[/]
global-shortcut=['<Control><Alt>v']
history-length=40
keep-search-entry=false
open-links-in-browser=false
paste-on-select=true
send-notification-on-copy=false
sync-primary=false
wiggle-indicator=false
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
['wintile@nowsci.com',
'pano@elhan.io']
```

**Comment by derevo** [comment]
Just a note that I updated the original bug report to show that the "Paste on Select" configuration in Pano seems to be the culprit. If you disable this (I do not remember if it is a default config, or not), then this problem no longer manifests.

So, if this is driving you as crazy as it has driven me, then at least there is a workaround.

**Comment by za-arthur** [comment]
I can confirm that this issue happens on my laptop too. I disabled "Paste on Select" to see if that helps.

**Comment by Tommimon** [comment]
Is this a duplicate of #244? The fix should already be merged and should land in next release.

**Comment by derevo** [comment]
@Tommimon , yes it does seem to be a duplicate, not sure why I couldn't find that issue previously. Thanks for pointing it out!

**Comment by Tommimon** [comment]
I'm glad this was what you were locking for!
If you don't want to wait for the new release you can patch it yourself, by editing `extension.js` and replacing:

`if (this.settings.get_boolean('paste-on-select')) {`

with

`if (this.settings.get_boolean('paste-on-select') && this.clipboardManager.isTracking) {`

I just tested this and it was on line `1073`.

You can see the same changes in the bottom of the [relative commit](https://github.com/oae/gnome-shell-pano/commit/24f4457e7605af2a621b21f109c7a25db8fc9ad3), but on the source file instead of `extension.js`
