### ISSUE TITLE
Clipboard content pasted automatically (without doing anything) after logging into the system

### ISSUE THREAD

**Issue by GerryT11** [oae/gnome-shell-pano#253]
## Description

**What is the bug?**

### Problem Explanation

When I log into the system (after suspend), the last clipboard content is automatically pasted in whatever text field is active. This happens automatically and no user activity is necessary. This bug is quite annoying and can cause privacy issues if the last clipboard content contained private/confidential information.

For example, 
(1) I use Slack, Firefox or whatever software, 
(2) then close the lid of the notebook, the notebook hibernates, I open the notbook again and enter my login password
(3) --> immediately Pano automatically pastes the clipboard content into Slack (or any other software that is open).

The bug happens always.

After disabling Pano, the problem does not happen anymore (there is no problem without Pano)

### Expected Behavior

No automatic pasting of clipboard content, but only when user wants/ initiates it.

### Question
Is this bug known? Is there any workaround available?

### System:
Ubuntu 23.10 (with Gnome45 and Wayland)
Most recent Pano release

**Comment by Pkcarreno** [comment]
This was already solved in https://github.com/oae/gnome-shell-pano/issues/244

You can wait until the new version rollout or you can use the workaround explained here https://github.com/oae/gnome-shell-pano/issues/251#issuecomment-1867696968

**Comment by GerryT11** [comment]
Thank you for pointing to issue 244. 
I close this issue here (as it is a duplicate).
