### ISSUE TITLE
Double click adds text to history

### ISSUE THREAD

**Issue by moritztim** [oae/gnome-shell-pano#257]
## Description

**What is the bug?**

### Problem Explanation
When Pano is enabled, any text I double click gets added to the history, but when I paste with `ctrl` `v` it pastes whatever I actually copied last.
![image](https://github.com/oae/gnome-shell-pano/assets/90388353/5348e5cb-139d-4db4-b7cd-ad201121c1a7)

### Expected Behavior

The history should contain only the actual clipboard history

### Steps To Reproduce

1. Enable pano
2. Clear the history
3. Copy something to the clipboard
4. Check the hstory to see only one entry
5. Double click on text
6. Check the history to see that the text is now in there, even tho it was only double clicked
7. Paste, to see that it's not actually in the clipboard

#### It happens with any application?

- [x] Yes, it applies to any application.
- [ ] No. Only with the following applications:
- [ ] It works with the following applications that I have tried:
n/a

#### It happens only on one computer?

- [ ] I don't know.
- [x] No. I have tried it on more than one computer.
both running arch linux

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:

## Diagnostics

**Under what conditions does it happen?**

### Environment

- GNOME Shell version: 45.4
- Distro: Arch
- Distro version: 6.6.16-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 21:20:21 +0000 x86_64 GNU/Linux

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
[no ouput when reproducing bug]
```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
[/]
global-shortcut=['<Super>v']
history-length=50
paste-on-select=true
play-audio-on-copy=false
send-notification-on-copy=false
show-indicator=false
sync-primary=true
```

#### Enabled Extensions

n/a

**Comment by hockdudu** [comment]
You have the setting "Sync primary" enabled. The "primary selection" means your text selection.

**Comment by moritztim** [comment]
Thank you
