### ISSUE TITLE
Can use Super+V

### ISSUE THREAD

**Issue by nosar77** [oae/gnome-shell-pano#258]
## Description

I would like to set Super+V to open pano as thats the some key that im used to on windows

### Problem Explanation

The problem is, I cannot set Super+V it doesn't register super by itself.

### Expected Behavior

What should happen is when I set a key shortcut I should be able to do Super+V however i  can only do CNTL+Super+V or any modifier before the super

**How one can find the bug?**

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Open setting
2. Try changing the Global Shortcut

#### It happens only on one computer?

- [X] I don't know.

#### It happens only with some specific gnome configuration?

- [X] I don't think that the configuration matters.

#### It happens only with some specific extension installed?

- [X] I don't think that the installed extensions affect the bug/behavior.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

- GNOME Shell version: Gnome 45.4
- Distro: EndeavourOS (Arch Based)
- Distro version: Galileo Neo

#### Application Version

Extension Versions 22

**Comment by nosar77** [comment]
I had assumed that the key was being overridden as well, but I check all my extensions and settings and didn't find a super +v. It works for other applications and I can set it for keys I for gssttings but it only doesn't work for me in pano. Unless there's a way to manually set it inside pano not sure how to fix it which is why I assumed it was a bug.

**Comment by e2ipi-1** [comment]
I can set this shortcut manually via
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/pano@elhan.io/schemas set org.gnome.shell.extensions.pano global-shortcut "['<Super>v']"
```
If that helps...

**Comment by nosar77** [comment]
Okay so that worked to actually set the key to Super+V but the command doesnt work at all, and in gsettings there is not a binding that uses Super+v this is weird.

**Comment by e2ipi-1** [comment]
For my part, I've chosen another way of using Pano, with two keyboard shortcuts, a method I share with you if it might be of interest to you or anyone else: in the "Keyboard" section of Ubuntu's settings, I have a shortcut "Super+Shift+v" (Super Paste) which executes the following script:

```
#!/bin/bash

gsettings --schemadir ~/.local/share/gnome-shell/extensions/pano@elhan.io/schemas set org.gnome.shell.extensions.pano paste-on-select 'true'
busctl --user call org.gnome.Shell /io/elhan/Pano io.elhan.Pano show
```
the panel opens, I select and it pastes directly ; and another shortcut "Super+Shift+c" (Super Copy) which executes the following script:

```
#!/bin/bash

gsettings --schemadir ~/.local/share/gnome-shell/extensions/pano@elhan.io/schemas set org.gnome.shell.extensions.pano paste-on-select 'false'
busctl --user call org.gnome.Shell /io/elhan/Pano io.elhan.Pano show
```
the panel opens, I select and it doesn't paste directly, I have to type "Ctrl+v". 
And as I sometimes use the indicator to open the panel, I've modified the `extension.js` file to switch to "paste-on-select" mode as soon as I click on the Pano indicator:

line added 
```
this.settings.set_boolean('paste-on-select', true);
```
just after the line
```
if (event.get_button() === Clutter.BUTTON_PRIMARY || event.get_button() === Clutter.BUTTON_MIDDLE) {
```
