### ISSUE TITLE
Copied files behave like links

### ISSUE THREAD

**Issue by neildarlow** [oae/gnome-shell-pano#26]
**Describe the bug**
When copying a file in Nautilus a file entry is created in Pano. If the file is deleted and then a Paste of the copied file is attempted an error is returned because the file no longer exists.

**Expected behavior**
If a file is copied then a physical copy of the file should be stored so that a subsequent paste returns the copied content not the content of the original file.

**Screenshots**
N/A

**To Reproduce**
- GNOME Shell version: 42.4
- Distro: fedora 36 Silverblue
- Steps to reproduce, if applicable:
1. Right-click a regular file in Nautilus and select Copy
2. Delete the file in Nautilus (Shift+Delete)
3. Attempt to paste the file entry from Pano and observe error dialog that file cannot be found.
4. Bug

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by oae** [comment]
This is intentional. I only store the file paths. If it is removed, Pano can not paste them. The amount of file operation required for this is too big.

**Comment by neildarlow** [comment]
So, it's OK to store images (which can be large too) but not regular files. Pfft...

**Comment by oae** [comment]
Images are different. I directly get them from the clipboard as byte data. For files, I am getting an array of paths. They can be really really big (eg. copying the whole user directory).
