### ISSUE TITLE
Can't find a translated term in the pt_BR.po file

### ISSUE THREAD

**Issue by msmafra** [oae/gnome-shell-pano#262]
I was looking to change the term "aproximadamente" to its abreviated form "aprox.", but I did not find it inside the pt_BR.po file.
Does Pano get it from external a source?

![flameshot-2024-03-01_13-01](https://github.com/oae/gnome-shell-pano/assets/1005457/d8fe5c44-7bf0-4964-b5d0-7c71b5a8e9af)

![flameshot-2024-03-01_13-40](https://github.com/oae/gnome-shell-pano/assets/1005457/9d8a0f9f-b92d-49f4-8ebd-ceb2cdc35ec6)

**Comment by oae** [comment]
Yes, Time-related translations are from https://github.com/date-fns/date-fns library
