### ISSUE TITLE
[BUG] Opening the content preview also opens the contextual menu

### ISSUE THREAD

**Issue by JE-Amouel** [oae/gnome-shell-pano#283]
## Description
**What is the bug?**
open content preview also open contextual menu.

### Problem Explanation
if i open content's preview, pano's contextual menu also appear. 

The bug happens when ...
i try to open content's preview with the mouse cursor only.

### Environment

- GNOME Shell version: 46
- Distro: fedoda
- Distro version: 40

### Screencast

[Screencast_05_16_2024_11:01:16_AM.webm](https://github.com/oae/gnome-shell-pano/assets/146543282/7bf7e1cb-2b48-4515-a2e4-579a7c5b1c41)

**Comment by Totto16** [comment]
> If I'm not mistaken, Pano is not yet compatible with Gnome 46

It is compatible, just not yet on EGO 😓  see #271

**Comment by Totto16** [comment]
> ## Description
> 
> **What is the bug?** open content preview also open contextual menu.
> ### Problem Explanation
> 
> if i open content's preview, pano's contextual menu also appear.
> 
> The bug happens when ... i try to open content's preview with the mouse cursor only.
> ### Environment
> 
>     * GNOME Shell version: 46
> 
>     * Distro: fedoda
> 
>     * Distro version: 40
> 
> 
> ### Screencast
> Screencast_05_16_2024_11.01.16_AM.webm

I noticed that too, but since I'm not here since the beginning, I always assumed, that that was intended like this, it looks really weird, when the panel is on the right, but if it's in the bottom it is alright. I sometimes use this feature, when I'm currently navigating with the mouse, instead of using the shortcut to open it. 🤷🏼‍♂️ 

@oae Was this intended like this, or not?

**Comment by oae** [comment]
It seems like the below commit broke this function. Only the right click should open the popup menu.

https://github.com/oae/gnome-shell-pano/commit/2361af0ba76b2b9c20853636fd3c1329bc6f140d#diff-5cedbb3beb837d1b671d8202c9dd333d301088645922f2a32ee7a82b1a69aebaL115-L125

**Comment by Malix-off** [comment]
@Totto16 
> It is compatible, just not yet on EGO 😓

Nice to hear it's halfway there
I don't know what "EGO" is thought

Gnome 46 display a tooltip that says
> This extension is incompatible with your current version of GNOME
![Screenshot from 2024-05-20 13-42-30](https://github.com/oae/gnome-shell-pano/assets/76160668/98ee008b-ab72-4ef3-b71b-09e32ccac6a1)

**Comment by Totto16** [comment]
> @Totto16
> 
> > It is compatible, just not yet on EGO 😓
> 
> Nice to hear it's halfway there I don't know what "EGO" is thought
> 
> Gnome 46 display a tooltip that says
> 
> > This extension is incompatible with your current version of GNOME
> > ![Screenshot from 2024-05-20 13-42-30](https://private-user-images.githubusercontent.com/76160668/332128842-98ee008b-ab72-4ef3-b71b-09e32ccac6a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjI2MzAsIm5iZiI6MTcxNjIyMjMzMCwicGF0aCI6Ii83NjE2MDY2OC8zMzIxMjg4NDItOThlZTAwOGItYWI3Mi00ZWYzLWI3MWItMDllMzJjY2FjNmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE2MjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNjVjY2U3MzkyNTcxYzRkZjA0NzQ2ZTQ1M2FkMmE2MmMyNzc0YjFjYWJlYzRkODA1MDI0MjA2NGEwODhkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B_mLR8wckcCOazY5ow2i4VOPT8gLAXBHxI8YpAg6ChM)

EGO refers to [https://extensions.gnome.org/](https://extensions.gnome.org/)

Yes, you need to compile it yourself atm unfortunately, see #271
