### ISSUE TITLE
Enhancement idea: Paste URLs without tracking (inspired from Firefox' new feature "copy without tracking")

### ISSUE THREAD

**Issue by GerryT11** [oae/gnome-shell-pano#289]
This is just an enhancement idea, not related to any bug.

It would be nice, if Pano had an option to paste URLs without tracking. Meaning that if Pano gets a URL with tracking information in the clipboard, it strips the tracking information from the URL and pastes only the actual URL without the tracking information. Pano could have an option in the preferences to "Always automatically remove tracking information from URLs"

Somewhere at Mastodon, I have seen people discussing about this possible enhancement to clipboard managers and it sounded very practical to me. The idea is inspired by the fairly new feature of Firefox to "copy without tracking", when the user wants to copy a URL from Firefox.

**Comment by Totto16** [comment]
This is already discussed in #198, I am closing this as a duplicate, feel free to comment on there.

A note on the feature, while it's not that bad of an idea, I have to cite 
https://github.com/oae/gnome-shell-pano/issues/198#issuecomment-1810062408 here, so maybe we'll add this as opt in, in the future.
