### ISSUE TITLE
Error on installing: SyntaxError: expected expression, got '.'

### ISSUE THREAD

**Issue by berkes** [oae/gnome-shell-pano#3]
Some of my specs (via neofetch)

```
OS: Ubuntu 20.04.4 LTS x86_64 
Host: N150ZU 
Kernel: 5.4.0-124-generic 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8565U (8) @ 4.600GHz 
GPU: Intel UHD Graphics 620 
Memory: 8597MiB / 15720MiB 
GPU Driver: i915 
```
Gnome versions:
```
❯ gnome-extensions --version
3.36.9
❯ gnome-shell --version
GNOME Shell 3.36.9
```

Stack trace: ``` _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33 OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28 asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13 run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20 main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13 run@resource:///org/gnome/gjs/modules/script/package.js:222:19 start@resource:///org/gnome/gjs/modules/script/package.js:206:5 @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17 ```

**Comment by berkes** [comment]
LibGDA is installed:

```
❯ apt show gir1.2-gda-5.0
Package: gir1.2-gda-5.0
Version: 5.2.9-2ubuntu1
[...]
Depends: gir1.2-freedesktop (>= 1.30.0), gir1.2-glib-2.0 (>= 1.30.0), libgda-5.0-4 (>= 5.2.2)
[...]
APT-Manual-Installed: yes
```

**Comment by oae** [comment]
Hi,

This extension doesn't support older gnome-shell versions. As I see, you have gnome-shell 3.36 installed.
________________________________
From: Bèr Kessels ***@***.***>
Sent: Friday, August 26, 2022 4:11:13 PM
To: oae/gnome-shell-pano ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oae/gnome-shell-pano] Error on installing: SyntaxError: expected expression, got '.' (Issue #3)


Some of my specs (via neofetch)

OS: Ubuntu 20.04.4 LTS x86_64

Host: N150ZU

Kernel: 5.4.0-124-generic

Resolution: 1920x1080

DE: GNOME

WM: Mutter

WM Theme: Adwaita

Theme: Yaru-dark [GTK2/3]

Icons: Yaru [GTK2/3]

Terminal: gnome-terminal

CPU: Intel i7-8565U (8) @ 4.600GHz

GPU: Intel UHD Graphics 620

Memory: 8597MiB / 15720MiB

GPU Driver: i915



Gnome versions:

❯ gnome-extensions --version

3.36.9

❯ gnome-shell --version

GNOME Shell 3.36.9



Stack trace: ***@***.***:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33 ***@***.***:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28 ***@***.***:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13 ***@***.***:///org/gnome/Shell/Extensions/js/dbusService.js:175:20 ***@***.***:///org/gnome/Shell/Extensions/js/main.js:19:13 ***@***.***:///org/gnome/gjs/modules/script/package.js:222:19 ***@***.***:///org/gnome/gjs/modules/script/package.js:206:5 @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by berkes** [comment]
If you can provide the minimal version that is required, I can prepare a small PR that adds this requirement to the README. 
I'm not familiar enough with the extensions system to find if I can add this as requirement to the extension code/metadata too. But the README would help, I think.

**Comment by oae** [comment]
Currently, the minimum version is 42. The thing is I don't want to support older versions because each version of gnome-shell has too many breakages. And it is a hassle to maintain.
