### ISSUE TITLE
Emoji with skin tone is not recognized as emoji

### ISSUE THREAD

**Issue by azzamsa** [oae/gnome-shell-pano#300]
## Description

Emoji with skin tone is not recognized as emoji

### Problem Explanation

If you copy a regular emoji such as 🙏, it is recognized as emoji.
But, it doesn't when you choose the same emoji with other skin tone such 🙏🏻

![image](https://github.com/oae/gnome-shell-pano/assets/17734314/7ca8840c-7a35-433e-b2ce-e56629ac6301)

### Expected Behavior

It should recognize both of them as emoji and display with the same size.

## Reprodution

- Copy a default emoji both with default skin tone and the other variations.
- Example: https://emojipedia.org/folded-hands-light-skin-tone

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Copy https://emojipedia.org/folded-hands
2. Copy https://emojipedia.org/folded-hands-light-skin-tone
3. See the difference

#### It happens with any application?

- [X] Yes, it applies to any application.
- [-] No. Only with the following applications:
  - VSCode
- [- ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [X ] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [ X] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [ X] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

**Comment by azzamsa** [comment]
We need to handle the additional byte for the skin tone. 
Related issue: https://github.com/hrsh7th/cmp-emoji/issues/11

**Comment by boerdereinar** [comment]
Fixed in #280 by just marking any single grapheme cluster as an emoji item.
![Screenshot from 2024-06-21 20-06-38](https://github.com/oae/gnome-shell-pano/assets/54003172/3e353fa7-5d3a-4c33-8c9f-8c3f8117374d)

**Comment by azzamsa** [comment]
Amazing work! Thank you. 🍜
