### ISSUE TITLE
Single-finger tap on icon opens clipboard AND top bar menu.

### ISSUE THREAD

**Issue by thyttan** [oae/gnome-shell-pano#303]
### BUG:
- Single-finger tap (left mouse button click) on icon opens clipboard AND top bar menu.
- Tap again hides the top bar menu.
- Tap a third time hides the clipboard.

### EXPECTED: 
To only display the clipboard. (One click should show. If I click again it should hide)

### SYSTEM
Fedora Linux 40
About 20 other extensions

Can anyone confirm they see this too?

Not sure if this only happens on Gnome 46 or on older versions as well.

**Comment by oae** [comment]
This might be fixed in https://github.com/oae/gnome-shell-pano/pull/285

**Comment by thyttan** [comment]
Ok, sorry for not finding that before filing the issue. To get the fix I'll need to build pano myself, right?

**Comment by Totto16** [comment]
> Ok, sorry for not finding that before filing the issue. To get the fix I'll need to build pano myself, right?

No, you can use the pre-release https://github.com/oae/gnome-shell-pano/releases/tag/v23-alpha2

**Comment by thyttan** [comment]
Thank you!
