### ISSUE TITLE
Images are not middle click pasteable

### ISSUE THREAD

**Issue by jdoss** [oae/gnome-shell-pano#31]
**Describe the bug**
If you create screenshot and it is copied to your clipboard, it is not pastable via middle click paste. It will use the last text based item in the list. This is most likely related to #30. I use Gpaste to sync the Clipboard buffer with Primary selection. You can turn on Image support in Gpaste but that will duplicate images items Pano and images are still not middle click pastable. 

**Expected behavior**
Images should be middle click pasteable via middle click from Primary Selection like Text.

**To Reproduce**
- GNOME Shell version: 42
- Distro: Fedora 36
- Steps to reproduce, if applicable:
 1. Hit print screen to take a screenshot. It will get copied to your Clipboard buffer.
 2. Try and middle click paste it.
 3. See the last text item you copypasta'ed get pasted instead of the image.

**Comment by oae** [comment]
We can track this issue in #30
