### ISSUE TITLE
Gnome 47 support

### ISSUE THREAD

**Issue by Edu4rdSHL** [oae/gnome-shell-pano#315]
**Is your feature request related to a problem? Please describe.**
As the title says, Gnome 47 support. The latest commit was intended to work on Gnome 46 (which never reached a stable version), but there's nothing regarding Gnome 47, afaik.

**Describe the solution you'd like**
Having the extension with Gnome 47 support on EGO.

**Describe alternatives you've considered**
At least some beta/rc release with the required changes (if needed) pointing to support Gnome 47.

**Additional context**
The current beta release that aimed at Gnome 46 **does** work fine on Gnome 47 RC, but I'm not sure if there's anything else that's needed to do for it to have the extension with Gnome 47 support on EGO instead of having to build manually from beta/git.

**Comment by Totto16** [comment]
I'll work on it soon 👍🏼

**Comment by Edu4rdSHL** [comment]
I have been finding these messages on the journal after a small system freeze:

```
Sep 25 10:08:39 SecHackLabs gnome-shell[2601]: [pano] [extension] extension is enabled
Sep 25 10:08:39 SecHackLabs gnome-shell[2601]: [pano] [pango] class names not found: hashbang
Sep 25 10:08:39 SecHackLabs gnome-shell[2601]: [pano] [pango] class names not found: hashbang
```

**Comment by Totto16** [comment]
> @Totto16 Just changing `resources/metadata.json` to add 47 as a supported version appears to work fine. Pano loads correctly and appears to be working correctly as it did before I updated. I haven't done extensive testing however.
> 
> ```diff
> diff --git a/resources/metadata.json b/resources/metadata.json
> index aead2f6..66776fb 100644
> --- a/resources/metadata.json
> +++ b/resources/metadata.json
> @@ -9,5 +9,5 @@
>    },
>    "settings-schema": "org.gnome.shell.extensions.pano",
>    "url": "https://github.com/oae/gnome-shell-pano",
> -  "shell-version": ["45", "46"]
> +  "shell-version": ["45", "46", "47"]
>  }
> ```

That seems promising, there are little changes, that may affect pano, but some are, I am looking into them  and also test them extensively 👍🏼

**Comment by Totto16** [comment]
> class names not found:

That's only a color error for code highlighting, and only a warning, but that will be obsolete soon ™️  with #278

**Comment by Totto16** [comment]
I added support for gnome 47 in #316. I also tested it extensively myself, but it would help, if you also test it, especially if you are not using fedora 41, but some other distro that already has gnome 47.

So to test it, either:
- Use the attached zip:
[pano@elhan.io.zip](https://github.com/user-attachments/files/17152086/pano%40elhan.io.zip)

Extract the contents of `pano@elhan.io.zip` into `$HOME/.local/share/gnome-shell/extensions/pano@elhan.io` eventually overwriting the old contents there. Then you can restart the shell session (logging out will suffice) and you have the new version.
 
- Or build the extension yourself, on the branch [gnome_47_support](https://github.com/oae/gnome-shell-pano/tree/gnome_47_support)

See [README#build](https://github.com/oae/gnome-shell-pano?tab=readme-ov-file#build) for more information on that

**Comment by Totto16** [comment]
Reopened this, to eventually fix things, if there should be issues, which there really shouldn't be, but who knows 🤷🏼‍♂️

**Comment by edubxb** [comment]
Downloaded and testing it on Debian Testing (Trixie).

Thanks for all the hard work making this awesome extension. I can't live without it! 🤩

**Comment by zsolt-donca** [comment]
It works for me on Arch on Gnome 47 using the AUR package [gnome-shell-extension-pano-git](https://aur.archlinux.org/packages/gnome-shell-extension-pano-git). I will report any issues that I encounter (none so far).

**Comment by literon36** [comment]
Using the release zip on Gnome 47 has no issues on my Arch machine!
Thank you so much for providing this great extension and the ongoing support! Also couldn't live without it <3

**Comment by Totto16** [comment]
It seems as it works flawlessly 😄, so I'll close this issue

**Comment by logicito** [comment]
In Extension Manager I still don't see Pano as an Extension to install, it's only possible up to Gnome 45, will this be updated? Using Fedora 41 Silverblue, thank you very much

**Comment by Axel29** [comment]
Hi, I installed it on Ubuntu 24.10 with Gnome 47 using the release [v23-alpha4](https://github.com/oae/gnome-shell-pano/releases/tag/v23-alpha4) , I can display the interface, but it is always empty, no matter what I add to my clipboard.

Does anyone have a fix for that please?

Thank you. 🙏
