### ISSUE TITLE
feature: audio-visual indicator

### ISSUE THREAD

**Issue by bennypowers** [oae/gnome-shell-pano#32]
**Is your feature request related to a problem? Please describe.**
The user is likely to save entries containing sensitive information to the clipboard history without realising it.

**Describe the solution you'd like**
Play a sound or show a notification when copying, so that the user is made aware that an entry has been saved in the history

**Describe alternatives you've considered**
an audio notification is ideal for users who are able to use audio, but if they are not, a visual notification should be provided as well, and ideally the preference between either or both should be made available

**Additional context**
paste.app for macos has a similar feature, as does clipboard indicator shell extension

**Comment by ecnivo** [comment]
Alternatively, other clipboard managers allow you to blacklist some programs -- for example, I've set CopyQ to ignore items from my password manager: https://copyq.readthedocs.io/en/latest/faq.html#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager
