### ISSUE TITLE
pano will record the selected text

### ISSUE THREAD

**Issue by everyx** [oae/gnome-shell-pano#325]
## Description

**What is the bug?**
pano will record the selected text, which will lead to many invalid records.

### Problem Explanation

Write a clear and concise description of what the bug is:

The bug happens when selecting a piece of text, any selected text will be recorded by pano, whether in Firefox or gnome-text-editor.

### Expected Behavior

A clear and concise description of what you expected to happen, and how the actual outcome differs:

- Pano shouldn't record selected text
- It should only record what is in the clipboard

## Reprodution

**How one can find the bug?**

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Open gnome text editor or any other application
2. Select some text
3. Press the shortcut `<super>` `v` to make pano panel show up
4. The selected text will be displayed in the pano panel

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [x] Yes, it applies to any application.

#### It happens only on one computer?

- [x] I don't know.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

- GNOME Shell version: GNOME Shell 47.1
- Distro: Arch Linux
- Distro version: rolling

### Screenshots

If applicable, add screenshots to help explain your problem:

https://github.com/user-attachments/assets/d065017d-0ef7-4575-a623-b25c31b3fbd4

#### Gnome

**Command:** `journalctl --since=now --follow /usr/bin/gnome-shell`

``` bash
$ journalctl --since=now --follow /usr/bin/gnome-shell
nothing
```

#### Pano Configuration

**Command:** `dconf dump /org/gnome/shell/extensions/pano/`

``` bash
$ dconf dump /org/gnome/shell/extensions/pano/
[/]
global-shortcut=['<Super>v']
history-length=20
is-in-incognito=false
item-date-font-family='Sans'
item-date-font-size=11
item-size=200
item-title-font-family='Sans'
item-title-font-size=20
link-previews=false
paste-on-select=false
play-audio-on-copy=false
search-bar-font-family='Sans'
search-bar-font-size=14
send-notification-on-copy=false
shortcut=['<Super>v']
show-indicator=false
sync-primary=true
watch-exclusion-list=true
wiggle-indicator=false
```

#### Enabled Extensions

**Command:** `dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'`

``` bash
$ dconf read /org/gnome/shell/enabled-extensions | tr ' ' '\n'
['timepp@zagortenay333',
'desktop-cube@schneegans.github.com',
'windowIsReady_Remover@nunofarruca@gmail.com',
'GPU_profile_selector@lorenzo9904.gmail.com',
'gnome-shell-screenshot@ttll.de',
'advanced-alt-tab@G-dH.github.com',
'BingWallpaper@ineffable-gmail.com',
'emoji-selector@maestroschan.fr',
'just-perfection-desktop@just-perfection',
'color-picker@tuberry',
'user-theme@gnome-shell-extensions.gcampax.github.com',
'drive-menu@gnome-shell-extensions.gcampax.github.com',
'autohide-battery@sitnik.ru',
'shuzhi@tuberry',
'ibus-tweaker@tuberry.github.com',
'noannoyance@daase.net',
'blur-my-shell@aunetx',
'gnome-compact-top-bar@metehan-arslan.github.io',
'date-menu-formatter@marcinjakubowski.github.com',
'ibus-switcher@kevinhwang91.github.com',
'Battery-Health-Charging@maniacx.github.com',
'legacyschemeautoswitcher@joshimukul29.gmail.com',
'Hide_Activities@shay.shayel.org',
'bluetooth-quick-connect@bjarosze.gmail.com',
'custom-accent-colors@demiskp',
'auto-move-windows@gnome-shell-extensions.gcampax.github.com',
'cronomix@zagortenay333',
'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
'mediacontrols@cliffniff.github.com',
'nightthemeswitcher@romainvigier.fr',
'appindicatorsupport@rgcjonas.gmail.com',
'power-profile-switcher@eliapasquali.github.io',
'dict@sun.wxg@gmail.com',
'gsconnect@andyholmes.github.io',
'pomodoro@arun.codito.in',
'pano@elhan.io']
```

**Comment by NinZeige** [comment]
This is not a bug, but rather intended behavior.
You should take some time to learn about the Linux clipboard system. This [Q&A](https://unix.stackexchange.com/questions/139191/whats-the-difference-between-primary-selection-and-clipboard-buffer) might be very helpful for you.

In short, this behavior occurs because you selected the "sync-primary" option in the settings. This is entirely expected. If you do not want this behavior, simply disable that setting.

**Comment by everyx** [comment]
> This is not a bug, but rather intended behavior. You should take some time to learn about the Linux clipboard system. This [Q&A](https://unix.stackexchange.com/questions/139191/whats-the-difference-between-primary-selection-and-clipboard-buffer) might be very helpful for you.
> 
> In short, this behavior occurs because you selected the "sync-primary" option in the settings. This is entirely expected. If you do not want this behavior, simply disable that setting.

Thank you for your answer @NinZeige
