### ISSUE TITLE
Support for Gnome 47

### ISSUE THREAD

**Issue by rgoubet** [oae/gnome-shell-pano#327]
Pano no longer works with Ubuntu 24.10, which runs Gnome 47.

Can something be done so that Pano no longer stops working at every Gnome major version?

**Comment by Totto16** [comment]
We already support gnome 46, just not trough [EGO](https://extensions.gnome.org/)

For more information see #315

See e.g. https://github.com/oae/gnome-shell-pano/issues/315#issuecomment-2377374470
