### ISSUE TITLE
Retain rich/formatted text (eg. bold, italics, HTML, etc.)

### ISSUE THREAD

**Issue by ecnivo** [oae/gnome-shell-pano#33]
**Is your feature request related to a problem? Please describe.**
Steps to reproduce:
1. Run Pano
2. Select and copy some rich-HTML (eg. part of this Github Issues webpage)
3. Copy another thing, doesn't matter. (this moves the rich-text HTML out of the OS clipboard, and only into Pano. Pano strips formatting at this point.)
4. Select the rich text snippet in Pano
5. Paste into Libreoffice Writer or similar -- the rich text formatting is gone

**Describe the solution you'd like**
Upon step 5, retain the rich text formatting

**Describe alternatives you've considered**
Before trying Pano, I was a user of CopyQ, which supports retaining rich text. A screenshot of the preview of retention of rich text is shown: 
![image](https://user-images.githubusercontent.com/10538710/187799038-dee9e081-0fb9-4695-9a65-34b8f5401a5e.png)

I'm really digging the better UI and visuals in Pano! I hope it can be made more feature-rich to compete with existing solutions :)

**Comment by oae** [comment]
Hi, Thank you for the report. I am not sure how I can achieve this with gnome-shell. But I will experiment on this.
