### ISSUE TITLE
Add Item Type Filter

### ISSUE THREAD

**Issue by derevo** [oae/gnome-shell-pano#333]
**Is your feature request related to a problem? Please describe.**
There are a number of times that I want to find a specific type of item, like image or URL, in my history but I don't have an easy way to limit my history and/or search to just that type.

**Describe the solution you'd like**
I think it'd be great to have a "type" filter available near the search box to be used for restricting the visible history to the selected type.

**Describe alternatives you've considered**
It would also be possible to only allow for filtering when using the search feature itself

**Additional context**
Example of UI component (but not actual filtering functionality)
![pano-filter](https://github.com/user-attachments/assets/6dc0c3f9-3c18-49e7-9286-08b9a6f1f73f)

Thank you for your consideration! I hope that I can open a pull request for this myself, time permitting.

**Comment by Totto16** [comment]
We already have that feature, just click on the search icon on the left of the textual search 😉

**Comment by derevo** [comment]
@Totto16 - that's awesome, thank you! This is a feature I simply missed in the documentation, and it's not clear in the UI that the functionality exists. The functionality itself is awesome, and I'm sure I will use it all the time, I guess I would just suggest making it more visibly obvious in the UI itself; however, I'm not a UX designer and other than what I've suggested here, I'm not sure what would be any better than what's already implemented, if anything.

Thanks for pointing this out and sorry for not reading thoroughly! :smile:
