### ISSUE TITLE
Remove dependency on libgda

### ISSUE THREAD

**Issue by hferreiro** [oae/gnome-shell-pano#36]
Ideally, GNOME extensions should be able to work standalone, especially for distributions like Fedora Silverblue, where installing additional packages can be more cumbersome.

**Comment by oae** [comment]
Thank you for the report. I tried different solutions at first but this was the best possible way. libgda is the data access library that allows me to store clipboard history and query them using SQLite. It is not possible to remove it.

**Comment by hferreiro** [comment]
Thank you for taking it into consideration. Please, also take into account that libgda is only used by very few packages (3 in Fedora), so very unlikely to be installed. I hope you find a replacement in the future.

**Comment by azzamsa** [comment]
@hferreiro same story here. What is your last resort?

**Comment by hferreiro** [comment]
@azzamsa Not using it currently.

**Comment by azzamsa** [comment]
@hferreiro may I know what you are using? CopyQ had some issue on Wayland https://github.com/flathub/com.github.hluk.copyq/issues/54
