### ISSUE TITLE
[Features] Shortcut for moving between clips/history, ability to pin(📌) clips/history

### ISSUE THREAD

**Issue by MuhametSmaili** [oae/gnome-shell-pano#38]
**Is your feature request related to a problem? Please describe.**
---
Currently, I do not see support for some of the features that are implemented in older clipboards, I think adding those features would improve a lot the overall extension, and also make users possible to completely move to this awesome extension.
The reason I think these features should be considered is because most of the people that use clipboard-clipper, use shortcuts, for faster moving between history, to increase productivity. The extension is awesome, especially since it saves images too, but when I started to use it (moved from the clipboard history) I am missing these features, and making me think to move back.  

**Describe the solution you'd like**
---
Here is like a list that shows some of the features to be implemented (those features are available in the other clipboards)

- [ ] Adding shortcut for moving to the history without opening the extension
   - For example the other clipboards have the option to move to the copied clipboard with a shortcut, this is better and also a feature that I think all the users will use. 
   - Pressing a shortcut (should be able to be customized) will move to upper/lower clipboard history and also should notify the user with which history he selected.
- [ ] Ability to pin the clipboard history. 
   - Add the possibility to pin some clipboard history, those can be on top always.

**Describe alternatives you've considered**
---
1. The first feature is more straightforward, just the option to move between the history/Database with shortcuts. The best is to add options inside the extension-option-window so that everyone can change shortucts in their own way. But showing notification that which clipboard you have now, (small text of the copied clipboard) is really good and better for user. If its image, we can notify the user that he selected an image like: `You selected an image`.

2. Second feature can be a bit not so good if people start to pin lot of history, (because the history is shown in big boxes) but this can be improved with a small UI/UX change. For example the pinned history, you can limit to not show the whole copied text, but put inside on one block with type of `pinned` and they should be shown just some parts (check the screenshot down for a better understanding of what i mean) 
   - This UI/UX feature be considered for implementation later if it is a better approach, now you can just add `pin` option, and leave pinned to the top

**Additional context**
---

![image](https://user-images.githubusercontent.com/51492002/187893884-3870e8e2-eb86-4051-b7ee-3f596ecba4f6.png)

**Comment by azzamsa** [comment]
Pinned history is very useful for many use cases. I hope it will land on `master` soon.

**Comment by JoseBritto** [comment]
This and feature request https://github.com/oae/gnome-shell-pano/issues/19 serve almost the same function.

**Comment by oae** [comment]
The first idea sounds good. I can add a shortcut that navigates each item in history. But I am not sure what would be a good solution for showing the selected item in the notification. There are many item types in Pano(file cut, file copy, url, color, image, text).

For the second, I could add a new tab alongside the current one that only shows pinned/favorited items in pano. This tab can also be opened with a shortcut.

**Comment by MuhametSmaili** [comment]
> The first idea sounds good. I can add a shortcut that navigates each item in history. But I am not sure what would be a good solution for showing the selected item in the notification. There are many item types in Pano(file cut, file copy, url, color, image, text).
> 
> For the second, I could add a new tab alongside the current one that only shows pinned/favorited items in pano. This tab can also be opened with a shortcut.

### For the notifications:
I'm aware that there are many types, which makes your extension one of the most valuable. I would suggest just a simple notification, for example, if is a file (it does not matter if it's copy/cut) when the global shortcut is pressed to show: `You selected file`. if it's an image: `You selected the image`, and so on. 
- **Extra**: If it's a text you could show some of the `beginning parts of the text`.
- **Extra**: if its type file/image you could show: `You selected file/image` and down the `file/image path of the selected item`. 
> The idea of notification is that the user knows he selected and shortcut fired.  



### For the tab idea: 
I think that works too. It's straightforward and less complicated to use.

**Comment by azzamsa** [comment]
> I think that works too. It's straightforward and less complicated to use.

During my time with  CopyQ, I never pin anything. I just create two tab. One for general purpose, The second for "pinned" message. I don't want to press down arrow multiple time to skip the pinned message if I have only one tab.

I agree with this approach.

**Comment by oae** [comment]
Now you pin items with `ctrl` + `s` or using :star: icon and switch between all items/favorites with `alt` key
![image](https://user-images.githubusercontent.com/1043714/222009351-0d20452b-ebfe-419e-936c-b49a2f8d92fa.png)
