### ISSUE TITLE
feature: make background colors more dark theme friendly

### ISSUE THREAD

**Issue by gmankab** [oae/gnome-shell-pano#40]
the background color of the copied text and files is too bright, please make them darker
![a](https://user-images.githubusercontent.com/73340745/187991688-720b366a-f3f4-4657-b8e3-6e2cd103590f.png)

**Comment by oae** [comment]
I will add customization related features later.

**Comment by oae** [comment]
You can now customize each item however you like.

![image](https://user-images.githubusercontent.com/1043714/222929945-1409dead-f3c4-4b54-a87f-19494dfffaac.png)

**Comment by gmankab** [comment]
Thank you :)
