### ISSUE TITLE
Feature: Exclude apps and exclude password managers by default

### ISSUE THREAD

**Issue by lijamez** [oae/gnome-shell-pano#41]
**Is your feature request related to a problem? Please describe.**
Copied data from some applications, such as password managers, are almost always sensitive. Pano should *never* store data when clipboard data comes from these types of apps. 

**Describe the solution you'd like**
Pano should provide a way for the user to configure a list of applications to exclude. Picking an application should be really simple (i.e. don't require the user to navigate to a application binary). 

Building on top of the above, Pano should also be shipped with a list of common applications which will be excluded **by default**. This is to make the extension "just work" the way that most people would probably want. The user always has the option to remove apps from the default exclusion list. 

**Describe alternatives you've considered**
There's already a feature request to add an expiry time to clipboard data, but that still leaves a time window where sensitive information is vulnerable.

**Additional context**
I have previously used Paste ( https://pasteapp.io/ ), a macOS app, and Paste can exclude certain apps and can exclude well known password management apps by default.

Some apps into put into the default exclusion list are:
- 1Password
- Bitwarden
- KeepassXC

**Comment by JoseBritto** [comment]
I don't know if pano already does this but from my small research I found this: 
[Code](https://github.com/keepassxreboot/keepassxc/blob/bdeef63fe4147e71f2f6bf387468a8c54312ee19/src/gui/Clipboard.cpp#L61) [Pull request](https://github.com/keepassxreboot/keepassxc/pull/1969)

That is a flag set by keepassxc to tell kde's password manager that the copied string is a secret. I don't use kepassxc or kde so I haven't tested it but if it works like that then I think it would be good for pano to support that too which would provide the added benefit that other password managers doing the same thing will also be included without any extra work.

**Comment by oae** [comment]
As I checked, gnome-shell clipboard API doesn't expose the clipboard owner. And most password managers don't set this flag you mentioned. I can try to exclude apps if they are the focused app when an item is copied, but this approach will not handle password managers that run in the other applications (as a chrome extension, or in the terminal app).

**Comment by lijamez** [comment]
> As I checked, gnome-shell clipboard API doesn't expose the clipboard owner. And most password managers don't set this flag you mentioned. I can try to exclude apps if they are the focused app when an item is copied, but this approach will not handle password managers that run in the other applications (as a chrome extension, or in the terminal app).

I think this is a fair compromise given the API limitations.

**Comment by Grafcube** [comment]
What about a toggle and a keybinding to toggle recording the clipboard? When I used copyq, I would manually disable clipboard sharing when dealing with secrets. It's less convenient but it addresses browser extension and terminal.

**Comment by JoseBritto** [comment]
> What about a toggle and a keybinding to toggle recording the clipboard? When I used copyq, I would manually disable clipboard sharing when dealing with secrets. It's less convenient but it addresses browser extension and terminal.

Making it so that it is accesible from the clipboard ui instead of extension settings would be nice.

**Comment by oae** [comment]
I plan to implement incognito mode. I will bind that functionality to a keyboard shortcut.

**Comment by azzamsa** [comment]
Nice solution. Incognito mode solves many weird approach  to exclude app.
Thanks a lot for your handwork for Pano!

**Comment by oae** [comment]
I also added `x-kde-passwordManagerHint` mime-type exclusion as @JoseBritto  suggested. Pano will ignore if any password manager sets clipboard content with this mime type. If there are other ones specific, I can add them too.
