### ISSUE TITLE
Feature: Save Entries with Tags

### ISSUE THREAD

**Issue by lijamez** [oae/gnome-shell-pano#42]
**Is your feature request related to a problem? Please describe.**
Sometimes there are certain snippets that I would like to refer to over a long period of time. Currently, any clipboard data that Pano stores in its DB will eventually be cleared due to the History Length.

**Describe the solution you'd like**
I would like to be able to pick some clipboard data to be permanently stored in Pano. 

This can be achieved by tagging the data by right clicking the snippet and choosing an existing tag or creating a new tag. Every tag should have a color as a visual aid. Retention of untagged data will still be subject to the History Length, but tagged data will never be evicted from the Pano database.

All tags are displayed in Pano when opened using the Global Shortcut. 

By default, Pano will display the clipboard history, as is the current behavior. However, the user will have an option to choose a tag and all of their tagged snippets will be available to store into the clipboard again. Tagged data can be reordered to the user's preference.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by MuhametSmaili** [comment]
This issue is related:
- #38

**Comment by oae** [comment]
Now you pin items with `ctrl` + `s` or using :star: icon and switch between all items/favorites with `alt` key
![image](https://user-images.githubusercontent.com/1043714/222009351-0d20452b-ebfe-419e-936c-b49a2f8d92fa.png)
