### ISSUE TITLE
feture: Paste on selection

### ISSUE THREAD

**Issue by mpetuska** [oae/gnome-shell-pano#5]
It would be great if I could configure the extension not only make clipboard history item active on selection, but also to immediately paste it (to avoid an extra CTRL+V)

**Comment by oae** [comment]
It is on my backlog :)

**Comment by mpetuska** [comment]
Awesome. https://github.com/SUPERCILEX/gnome-clipboard-history has implemented that already if you're looking for inspiration.

**Comment by PranavBhattarai** [comment]
Yeah, it makes sense. An option to enable such behaviour would be great.

**Comment by MaCroX95** [comment]
+1 for this feature!

**Comment by gmankab** [comment]
> Awesome. https://github.com/SUPERCILEX/gnome-clipboard-history has implemented that already if you're looking for inspiration.

but it don't support images

diodon have this feature and support images, but diodon have 1 second lag while pasting item

**Comment by SanpuiRonak** [comment]
@oae are you already working on it? if not then i could make a PR

**Comment by brunnobb** [comment]
+1 as it increases a lot my workflow

**Comment by oae** [comment]
I will release this in v6. You can track the milestone [here](https://github.com/oae/gnome-shell-pano/milestone/2)

**Comment by azzamsa** [comment]
> [oae](https://github.com/oae) closed this as [completed](https://github.com/oae/gnome-shell-pano/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/oae/gnome-shell-pano/commit/6aa3bc03ebf86f1b1af9e5eb339f5c08c6f1a2c4 [21 hours ago](https://github.com/oae/gnome-shell-pano/issues/5#event-7361686457)

Wow, that fast! :rocket: 
Thank you for your handwork for Pano!

**Comment by MrMiracles** [comment]
Sorry, but I have a question on this topic. 
For the love of God, I can't find out how this is supposed to work? I make a selection, the selected text gets copied to the clipboard and then what? How and where is it pasted with this function on? I can't get it to work. Thanks to anyone who can explain this function to me and makes my life a little easier :-)

**Comment by mbeko** [comment]
@MrMiracles I had the same question, found this issue and in the end figured out myself by looking at the code.

I was first confused by the word "select" because I associated it with selecting the text with the mouse. However, what is meant here by "select" is picking an entry in the clipboard manager. If you do that, Pano will automatically press Ctrl+V for you.

So for example, if you're in a text field, open the clipboard manager and click on a text entry, the text will be pasted in that text field.

**Comment by MrMiracles** [comment]
> @MrMiracles I had the same question, found this issue and in the end figured out myself by looking at the code.
> 
> I was first confused by the word "select" because I associated it with selecting the text with the mouse. However, what is meant here by "select" is picking an entry in the clipboard manager. If you do that, Pano will automatically press Ctrl+V for you.
> 
> So for example, if you're in a text field, open the clipboard manager and click on a text entry, the text will be pasted in that text field.

Thanks mate!
