### ISSUE TITLE
Incorrect detection of code blocks.

### ISSUE THREAD

**Issue by JoseBritto** [oae/gnome-shell-pano#52]
**Describe the bug**
Pano incorrectly classifies a wall of text as code and an actual java code snippet as text.

**Expected behavior**
It correctly identifies code blocks.

**Screenshots**

![image](https://user-images.githubusercontent.com/64070234/188664618-69de653f-dded-4fdb-9cc9-a911d7b05387.png)

**To Reproduce**
- GNOME Shell version: 42.4
- Distro: Endeavour OS

Sample text (is detecting as code):
```
This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. 

This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. 
This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. 

This is a sample wall of text. Clearly this is not code. I think that is obvious. This is a sample wall of text. Clearly this is not code. I think that is obvious. 
```

Sample code (is detecting as text):
```
class Java
{
   public static void main(String[] args)
   {
      System.out.println("Clearly this is code sniippet");
   }
}
```

**Comment by oae** [comment]
This is really hard to detect. I use highlight.js to determine the language but it is not always accurate. Also, I experimented with guesslang models that vscode uses to detect the code. That seems a little bit better but extension bundle size skyrockets(because of TensorFlow dependencies). I am open to ideas about other solutions.

**Comment by oae** [comment]
I am considering removing code blocks.
