### ISSUE TITLE
First element selected by default

### ISSUE THREAD

**Issue by marcinjahn** [oae/gnome-shell-pano#54]
**Is your feature request related to a problem? Please describe.**

When I open the Pano panel, I see this:

![image](https://user-images.githubusercontent.com/10273406/188955427-58dfd8e5-7628-49f9-8c32-8b295f223faf.png)

Now, in order to copy the second element from the left, I have to go right with two right-arrow clicks. However, I believe it should be just one right-arrow click. Logically, the element that is on the very left is already in my clipboard. So, I'd never need to select it and copy it. The minimum amount of right-arrow clicks that I will realistically ever do in Pano is two clicks.

**Describe the solution you'd like**

Select the very first element by default so that a single right-arrow click will take me to the second element.
I think such a setting should be configurable so that people who like the current approach may keep it.

**Describe alternatives you've considered**

I think the current approach is a bit inefficient. The proposed solution should get rid of this one unneeded click.

**Additional context**

Probably it makes sense how other similar tools do it.

**Comment by G-dH** [comment]
The default initial selection should be on the second item since the first one should be already in the clipboard.

**Comment by marcinjahn** [comment]
Right, that would actually be the most “optimized” flow. I’d prefer that to be configurable though.
