### ISSUE TITLE
Pano gets not correctly shown in multi monitor setups

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [oae/gnome-shell-pano#55]
**Description**
When using Pano in a multi monitor setup, Pano get only shown correctly on the monitor that has the gnome top menu bar. On the other it appears and disappears when using the activation shortcut.

**Expected behavior**
Pano should show correctly on any monitor I am.

**Screenshots**
Because of the nature of this problem it is not possible to screenshot it.

**How to Reproduce**
- GNOME Shell version: 42
- Distro: Fedora 36
- Number of monitors: 2, they where connected to a thunderbolt dock from dell. They where also identical units.
- Steps to reproduce, if applicable:
1. Open Pano on the screen with the menu bar. This works fine.
2. Open Pano on a different screen. Now Pano appears and disappears immediately.

**Log data**
I can't provide any l,og data as I am not at my work place right now. I will try to add log data later.

**Comment by oae** [comment]
I am not able to reproduce this issue. I have a dual monitor setup also. Pano always opens where my mouse is.

**Comment by Sebastian-Hirsch** [comment]
When I am back at my multi monitor setup, I will test this again. I will let you know how it goes.

**Comment by Sebastian-Hirsch** [comment]
I cannot reproduce this issue with the current version of pano anymore, so I will close this issue. Sorry for the late response, I am just right now able to use my multi monitor setup again.

**Comment by Dkoeddnsnp** [comment]
I have this issue under Wayland session with 2 monitors. On my primary 165hz screen (DP) pano opens properly. On the secondary 60hz display (HDMI) it just flashes and disappears.
