### ISSUE TITLE
Crashes on GNOME 43

### ISSUE THREAD

**Issue by FeyXieXzf** [oae/gnome-shell-pano#58]
**Describe the bug**
- When the extension is activated on gnome 43, the session instantly crashes and throws me back to the login screen.
- If tries to login when the extension is on, the login will fail and put me back to the login screen.
 
**Expected behavior**
The extension being turned on successfully and works well.

**Screenshots**
Cannot add screenshots since it is an instant crash.

**To Reproduce**
- GNOME Shell version: 43
- Distro: Arch Linux (up-to-date)
- Steps to reproduce, if applicable:
1. Install Pano
2. Activate it
3. Crashes

**Log data**
Couldn't find any data related to the crash.

**Comment by oae** [comment]
Pano does not support gnome 43 yet. I will add it later near the release

**Comment by AdsonCicilioti** [comment]
@oae Wouldn't it be better to close the issue when support arrives?

**Comment by oae** [comment]
> @oae Wouldn't it be better to close the issue when support arrives?

I have already released it.

**Comment by AdsonCicilioti** [comment]
> > @oae Wouldn't it be better to close the issue when support arrives?
> 
> I have already released it.

But here crash yet.

**Comment by oae** [comment]
You can create an issue with the necessary logs.

**Comment by AdsonCicilioti** [comment]
> You can create an issue with the necessary logs.

@oae How i can get the logs??
