### ISSUE TITLE
feature-request: Add GNOME 43 support

### ISSUE THREAD

**Issue by git-Hmmm** [oae/gnome-shell-pano#59]
**Describe the idea or feature you'd like**
I want this extension to be functional in gnome 43

**Is your feature request related to a problem? Please describe.**
nope

**Additional context**
nope

**Comment by oae** [comment]
Thank you for the request. I will add it near the gnome 43 release.

**Comment by FlyinPancake** [comment]
Does G43 break anything?

**Comment by git-Hmmm** [comment]
> @FlyinPancake Does G43 break anything?

Yes I tried to change version in metadata.json it works fine, but when you will try to paste something your gnome session will keep crashing.

**Comment by oae** [comment]
Libgda was the problem for the crashes I think. It is now working on gnome-shell 43

**Comment by git-Hmmm** [comment]
@oae when making release?
So that it becomes available on gnome extensions store.

**Comment by oae** [comment]
I have submitted the new release(v10) to EGO. It will be available soon.
