### ISSUE TITLE
feature : Be able to change height 

### ISSUE THREAD

**Issue by felipedobrinin** [oae/gnome-shell-pano#6]
I have an HD monitor, so the current height is almost half of my screen.
![image](https://user-images.githubusercontent.com/78673467/186985075-7f1acb2c-ac72-4613-b898-d51d056575d4.png)

An option to change the height would be great.

**Comment by oae** [comment]
Current height is 380px. Adding an option for it can be difficult. I won't promise anything but I will look into it.

**Comment by marcinjahn** [comment]
In general, it would be cool if the UI was a bit more responsive, allowing to change height and the number of items displayed.

**Comment by forteller** [comment]
Maybe the default height should not be set in pixels, but in percentage of the screen height?

**Comment by oae** [comment]
The new version will include this option

![image](https://user-images.githubusercontent.com/1043714/221446111-d74089ad-21ce-4ad8-a474-d7b52ec7db24.png)
