### ISSUE TITLE
gir1.2-gsound-1.0 is needed since last update

### ISSUE THREAD

**Issue by ChrisLauinger77** [oae/gnome-shell-pano#61]
After the update the extension stopped working for me.
I needed to install "gir1.2-gsound-1.0" (on debian with apt)
maybe upate the doc that not only "gir1.2-gda-5.0" is needed but also "gir1.2-gsound-1.0" ?

**Comment by azzamsa** [comment]
For fedora workstation, it works out of the box. I can't say about Fedora Everything (minimal install).

I think a PR would be better :)

**Comment by ChrisLauinger77** [comment]
What do you mean a PR ?

**Comment by azzamsa** [comment]
A Github Pull Request: [Contributing to projects - GitHub Docs](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)

**Comment by ChrisLauinger77** [comment]
And what should this PR contain ? I do not ask for a code change.
I asked for
maybe upate the doc that not only "gir1.2-gda-5.0" is needed but also "gir1.2-gsound-1.0" ?

**Comment by azzamsa** [comment]
A change to this line https://github.com/oae/gnome-shell-pano/blob/898b72c92cc8f193c3ccf9a8d0564bc45085022b/README.md?plain=1#L38

**Comment by oae** [comment]
@ChrisLauinger77 which distro do you use? I will add it to README. Gsound was the core dependency on Arch Linux (it comes with gnome-control-center).

**Comment by ChrisLauinger77** [comment]
I needed to install "gir1.2-gsound-1.0" (on debian with apt)
so debian (testing)

**Comment by oae** [comment]
I have added new instructions to readme
