### ISSUE TITLE
Doesn't work with libgda 6 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by kreaninw** [oae/gnome-shell-pano#7]
I installed all the dependencies needed:

```
$ sudo zypper se -i libgda
Loading repository data...
Reading installed packages...

S  | Name                    | Summary                                           | Type
---+-------------------------+---------------------------------------------------+--------
i+ | libgda-6_0-6_0_0        | GNU Data Access (GDA) Library                     | package
i  | libgda-6_0-6_0_0-lang   | Translations for package libgda                   | package
i  | libgda-6_0-ldap         | LDAP Provider for GNU Data Access (GDA)           | package
i  | libgda-6_0-mysql        | MySQL Provider for GNU Data Access (GDA)          | package
i+ | libgda-6_0-sqlite       | Sqlite Provider for GNU Data Access (GDA)         | package
i+ | libgda-6_0-tools        | GNU Data Access (GDA) Library -- Tools            | package
i+ | libgda-report           | GNU Data Access (GDA) Library                     | package
i  | libgda-report-6_0-6_0_0 | GNU Data Access (GDA) Library                     | package
i  | libgda-ui-6_0-6_0_0     | GNU Data Access (GDA) Library - UI Widgets        | package
i  | libgda-ui-6_0-plugins   | GNU Data Access (GDA) Library - Plugins for UI -> | package
i+ | libgda-xslt-6_0-6_0_0   | GNU Data Access (GDA) Library                     | package
i  | libgdata-lang           | Translations for package libgdata                 | package
i  | libgdata22              | GLib-based library for accessing online service-> | package
```
However, the extension still shows an error:

![Screenshot from 2022-08-26 20-37-39](https://user-images.githubusercontent.com/1403194/187007323-43e0884f-ddd5-4599-9040-ee5fa219af77.png)

**Comment by tklros** [comment]
I have exactly the same problem

**Comment by kevlugli** [comment]
You have to also install typelib-1_0-Gda-6_0, anyway after installing that I've got an "dm is null" error. #4 says that error happens in Gnome 43, but AFAIK Tumbleweed hasn't got that version yet.

**Comment by kreaninw** [comment]
> You have to also install typelib-1_0-Gda-6_0, anyway after installing that I've got an "dm is null" error. #4 says that error happens in Gnome 43, but AFAIK Tumbleweed hasn't got that version yet.

I installed `typelib-1_0-Gda-6_0`, still get the same error. I am on GNOME 42.4.

**Comment by austinrojers** [comment]
I am having the same issue in Arch, there doesn't seem to be any package 'typelib' in arch

**Comment by oae** [comment]
@austinrojers for Arch Linux you need to install `libgda` package. 

I will install OpenSuse and check the requirements on that distro. I mainly tested the extension with libgda version 5.2

**Comment by austinrojers** [comment]
So sorry. I somehow thought I had installed 'libgda', my bad.
Thanks, it is working now!
