### ISSUE TITLE
Describe why Pano tries to connect to the internet

### ISSUE THREAD

**Issue by Vinnl** [oae/gnome-shell-pano#71]
**Is your feature request related to a problem? Please describe.**
It's not clear what functionality you'll lose by enabling Offline mode. (I think it'll fetch preview images of links you have copied?)

**Describe the solution you'd like**
The settings description could be updated to describe the impact of enabling/disabling it. For example:

> When enabled, Pano will not try to connect to the internet to find preview images of links on your clipboard

**Describe alternatives you've considered**
Alternatively, I guess "enabling offline mode" also feels like a double negative ("disable to not connect to the internet"), which can be confusing. You could also consider changing it to "Link previews" that is _enabled_ by default, with a description like

> Allow Pano to visit links on your clipboard to generate link previews

**Additional context**
What it looks like now:

![image](https://user-images.githubusercontent.com/4251/189610784-7cd7d4cb-9e99-4efb-89c8-9e9a9019d090.png)

It also jumps out because it's the only disabled boolean preference by default:

![image](https://user-images.githubusercontent.com/4251/189610869-f2791046-857e-4771-b6e6-545cf52b3c86.png)

**Comment by oae** [comment]
Thank you for the suggestion. I changed it.

![image](https://user-images.githubusercontent.com/1043714/189616082-14c9c657-ea54-4d7e-978f-cf0b0a7ffa1e.png)
