### ISSUE TITLE
Hide top bar icon

### ISSUE THREAD

**Issue by LeGmask** [oae/gnome-shell-pano#72]
**Is your feature request related to a problem? Please describe.**
I hate top bar icon, I want a clean top bar, but since latest update seems like the topbar icon is always displayed

**Describe the solution you'd like**
A setting to disable topbar icon.

**Comment by oae** [comment]
You can disable it in the settings.

![image](https://user-images.githubusercontent.com/1043714/189615042-de05abb1-3eab-4328-9858-8f6be07c4ce2.png)

**Comment by SoMuchForSubtlety** [comment]
![image](https://user-images.githubusercontent.com/15961647/189615040-a3c7d0de-05f9-4f2b-a302-e8542949950c.png)
![image](https://user-images.githubusercontent.com/15961647/189615087-e89da6de-724c-4191-9861-49c73a9ce246.png)
