### ISSUE TITLE
Missing Danger Zone icon

### ISSUE THREAD

**Issue by michojel** [oae/gnome-shell-pano#74]
First of all, thanks for the great work!

**Describe the bug**
Danger Zone's icon (`app-remove-symbolic`) looks to be a part of Yaru theme which seems to be an unintentional dependency. Please check the screenshot below.

**Expected behavior**
The extension should not depend on a particular Gnome theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/21156022/189631792-89f81f6a-ba01-48db-a074-c8cc88722ab0.png)

**To Reproduce**
- GNOME Shell version: 42
- Distro: NixOS 22.05
- See https://github.com/NixOS/nixpkgs/pull/189091#issuecomment-1243505180

**Comment by oae** [comment]
I am using stock gnome without themes on Arch Linux. All distros that I tried (Arch Linux, Fedora, OpenSUSE, Ubuntu, Debian) contain this icon.

**Comment by oae** [comment]
As I checked, It comes from hicolor-icon-theme which is dependency of for adwaita-icon-theme and gtk4

![image](https://user-images.githubusercontent.com/1043714/189639212-298e1d0d-7ee8-46dc-a246-92931c0e833e.png)

**Comment by jtojnar** [comment]
`hicolor-icon-theme` should not contain any icons, it is just a scaffolding for other apps to install icons to. Can you try running `pacman -Qo app-remove-symbolic.svg`?

**Comment by oae** [comment]
![image](https://user-images.githubusercontent.com/1043714/189670021-d2691633-04ad-4aa2-b8c1-31e8164f8f32.png)

**Comment by jtojnar** [comment]
Actually, it looks like I have it on my system too and it comes from gnome-software: https://gitlab.gnome.org/GNOME/gnome-software/-/blob/b6e8ba694f2f8f6c4bd585667651cbb074d82049/data/icons/hicolor/meson.build

**Comment by oae** [comment]
is there a way to figure out which icons can be used when core gnome is on the system?

**Comment by michojel** [comment]
I see, gnome-software wasn't even installed on my system with the standard Gnome. Nevertheless, even if I add it as a runtime dependency for the extension, it won't be picked up unless I set Gnome's icon set to the one containing the icon.
As a package maintainer, I would probably have to patch the extension to use the full path to ensure the icon shows up. But that doesn't feel right, because then the icon doesn't adapt to the user's selected icon set/theme.

**Comment by jtojnar** [comment]
> is there a way to figure out which icons can be used when core gnome is on the system?

I would guess checking what [adwaita-icon-theme](https://gitlab.gnome.org/GNOME/adwaita-icon-theme) contains. Though in recent times, quite a lot of icons have been removed and the repo description says “Mostly private use system icons” so perhaps it is not meant to be used after all.

And the HIG just straight up recommends vendoring icons: https://developer.gnome.org/hig/guidelines/ui-icons.html#finding-ui-icons

> I see, gnome-software wasn't even installed on my system with the standard Gnome.

Yeah, we only install GNOME Software when user enables Flatpak, as the PackageKit integration is not yet usable.

> Nevertheless, even if I add it as a runtime dependency for the extension, it won't be picked

The build infrastructure no longer picks up icons from random packages, it just added noise.
