### ISSUE TITLE
Feature request: Left click on Top Bar Indicator to Toggle Pano directly

### ISSUE THREAD

**Issue by thyttan** [oae/gnome-shell-pano#75]
**Is your feature request related to a problem? Please describe.**
When pressing the top bar indicator I expect Pano to be toggled, i.e. display the clipboard. Instead the drop down menu for the indicator appears. As it is implemented now I need to do two clicks to show the clipboard with my touchpad/mouse.

**Describe the solution you'd like**
I suggest Left Click on Top Bar Indicator to toggle Pano, and Right Click on Top Bar Indicator to open it's drop down menu.

Again, great work on Pano - it's delightful! :)

**Comment by oae** [comment]
Thank you for the suggestion. I have changed the left/middle click to open Pano and right click to open the dropdown
