### ISSUE TITLE
feature: indicator in top panel

### ISSUE THREAD

**Issue by thyttan** [oae/gnome-shell-pano#8]
... clickable to open the clipboard, as a complement to using the keyboard shortcut. EDIT: Alternatively add hot corner functionality.

What a wonderful extension - thanks!

**Comment by oae** [comment]
Thank you for the suggestion. I will consider it.

**Comment by RedCommand** [comment]
It will be very nice if we can have a little preview of the last element in the panel in the clipboard like Clipboard History :
![image](https://user-images.githubusercontent.com/50780743/188111993-86e0e0f6-ac01-417a-b5bf-b92c3797d18d.png)
Pano is a way better extension but i really need to know when an item get copied in my clipboard.
As a work around i just let the Clipboard History extension installer with all shortcut set to disable but when i click on the little icon in the top panel, it is the Clipboard History 😢 . Also Clipboard History only handle text so if i copy a file or an image, the top icon does not handle it.
