### ISSUE TITLE
Pano stopped working on Ubuntu 22.04.1 after update

### ISSUE THREAD

**Issue by dsmalinsky** [oae/gnome-shell-pano#82]
First of all congrats for this excellent little piece of software, it's making my day to day more fun and pleasant :)

Sadly Pano stopped working on my PC running Ubuntu 22.04.1 after last extension update.

Error message is:
Requiring GSound, version none: Typelib file for namespace 'GSound' (any version) not found

Any ideas?

**Comment by oae** [comment]
Hi, 

Thank you for the kind words :smile: . You need gsound installed. [Here](https://github.com/oae/gnome-shell-pano#installation) you can find the installation instructions. 

For ubuntu run the following command and then logout and log back in. It should be working.

```bash
sudo apt install gir1.2-gda-5.0 gir1.2-gsound-1.0
```

**Comment by dsmalinsky** [comment]
It worked after that, thanks!
