### ISSUE TITLE
Pano doesn't support touch screen correctly

### ISSUE THREAD

**Issue by Midou36O** [oae/gnome-shell-pano#87]
**Describe the bug**
Pano doesn't let the user scroll and select a piece of text/image/etc. using touch screen.

**Expected behavior**
Pano should be able to handle touch screen movements and inputs correctyl.

**Screenshots**
*None*

**To Reproduce**
- GNOME Shell version: 42
- Distro: Artix Linux
- Steps to reproduce, if applicable:
1. Get a convertible laptop or a tablet that runs gnome.
2. Open the pano clipboard panel.
3. Attempt to select a piece of text or image, and try to scroll.
4. Realise it doesn't work and cry. 

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:

I run an operating system that doesn't use SystemD 😅
If there is a way to do the equivalent to this in OpenRC let me know and i will update the issue with the correct logs!

**Comment by amadeusp** [comment]
Just wanted to report the same issue. Any progress on this? :)

**Comment by Midou36O** [comment]
If you could provide the logs data this could help figuring out the problem, assuming you have systemd :)

**Comment by oae** [comment]
Well, I don't have any touchscreen devices. So PR's are welcome

**Comment by amadeusp** [comment]
I would love to help track this down. But how would I best approach this? Where and how are things like that logged and what information would be most interesting for you?

**Comment by SelfRef** [comment]
I just wanted to add I can't even open Pano using touch. The icon on the top bar doesn't open the panel when tapped. Other indicators work fine.

https://github.com/oae/gnome-shell-pano/assets/69125050/d5186291-9705-499c-8e24-d9cd5962f6ab

(when cursor is not visible, it's mean I'm using touchscreen)
