### ISSUE TITLE
The stated global shortcut doesn't change until settings are reopened

### ISSUE THREAD

**Issue by forteller** [oae/gnome-shell-pano#88]
Thanks for a beautiful and very useful tool!

**Describe the bug**
When changing the global shortcut the preview, or stated shortcut, in the settings window does not change. You have to close the window and then open it again for the change to appear, even though the actual change happens immediately. 

This is confusing, since it seems like nothing happened.

**Expected behavior**
The preview should change immediately

**Screenshots**

**To Reproduce**
- GNOME Shell version: 42
- Distro: Nobara Linux 36
- Steps to reproduce, if applicable:
1. Open settings
2. Click on Global Shortcut
3. Select a new shortcut
4. Notice that the preview does not match your new shortcut

**Comment by oae** [comment]
Thank you for the report. Good catch :)

**Comment by forteller** [comment]
You have an unbelievable response time! Thank you! :D
