### ISSUE TITLE
Issue: "TextDecoder not defined"

### ISSUE THREAD

**Issue by ServerCrashed** [oae/gnome-shell-pano#9]
I installed the extension from chrome using gnome extension and it gives an error saying "TextDecoder not defined". For the record, I have installed the gda package.

The settings of extension pano@elhan.io had an error:
```
Error: Requiring Adw, version none: Typelib file for namespace 'Adw' (any version) not found
```

Stack trace:
```
@/home/aks/.local/share/gnome-shell/extensions/pano@elhan.io/prefs.js:251:1
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by ServerCrashed** [comment]
I am on GNOME 43

**Comment by oae** [comment]
Currently, only gnome-shell 42 is supported. I will add 43 support in the future.

**Comment by ServerCrashed** [comment]
My bad, it is GNOME 42 😅

**Comment by oae** [comment]
Which distro do you use?

> Error: Requiring Adw, version none: Typelib file for namespace 'Adw' (any version) not found

libadwaita seems missing.

**Comment by ServerCrashed** [comment]
I use Zorin OS 16.1

**Comment by oae** [comment]
I will try Zorin OS in VirtualBox and let you know.

**Comment by ServerCrashed** [comment]
Alright. I appreciate your efforts. 
🤗

**Comment by oae** [comment]
I downloaded and checked it. It seems Zorin os uses an old version of gnome-shell. This extension only supports gnome-shell 42 right now.

![image](https://user-images.githubusercontent.com/1043714/187287646-0754b2c5-fc29-4572-8031-1270aaf830f5.png)

**Comment by ServerCrashed** [comment]
Oh. I see.

**Comment by Spl0itable** [comment]
@oae Hey! Any chance of supporting those? I'm in the same predicament with PureOS :/

Would love to use this extension if possible. Appreciate you building something like this!
