### ISSUE TITLE
Shortcut to directly paste clip nr X

### ISSUE THREAD

**Issue by forteller** [oae/gnome-shell-pano#90]
This is somewhat related to #38, but distinct I think.

While having Pano open I see 6 visible clips from the clipboard. It would be very helpful if I didn't have to navigate to the one I want and press enter to paste it, but could just immediately paste the one I want. This could be done trough pressing a modifier key + a number between 1-6, for example Ctrl+3.

If this is possible to implement it would also be nice if the number of the clip would be shown in the header of the clip, to help you recognize instantly which number you want to press to paste the one you want.

Thanks again! :)

**Comment by oae** [comment]
`ctrl` `1`..`9` keys will copy the item with the corresponding index.
