### ISSUE TITLE
Search UI doesnt match shell aesthetics

### ISSUE THREAD

**Issue by rohmishra** [oae/gnome-shell-pano#95]
**Describe the bug**
The CSS styling used by the extension and by the shell search bar looks different. 

**Expected behavior**
The search bar resembles the one from shell search

**Screenshots**
![image](https://user-images.githubusercontent.com/2221064/191633033-dac0d909-4cf7-42fc-b6f2-4a428b5e8a42.png)
![image](https://user-images.githubusercontent.com/2221064/191633041-80849b96-2924-44c8-815c-beb5d30ee186.png)

**To Reproduce**
- GNOME Shell version: 42
- Distro: Manjaro
- Steps to reproduce, if applicable:
Open the extension

**Log data**

**Comment by daudix-UFO** [comment]
But it matches the shell password prompt

![image](https://user-images.githubusercontent.com/77155297/210358531-52693079-3116-4930-b513-077d0847223f.png)
