### ISSUE TITLE
Having trouble to build from source 

### ISSUE THREAD

**Issue by felipedobrinin** [oae/gnome-shell-pano#97]
It says that Gda and GSound is not to be found, but I already have them installed
![image](https://user-images.githubusercontent.com/78673467/191665035-bf141807-9736-4bbf-a16c-29fc7bb0b00b.png)
![image](https://user-images.githubusercontent.com/78673467/191665175-5e8f18a7-955b-42ff-9e2c-ac8bcaa782b2.png)
any idea on what I am missing ?

**Comment by yilozt** [comment]
Your need install `gsound-devel` and `libgda-devel` in Fedora.

**Comment by felipedobrinin** [comment]
Thanks !
