### ISSUE TITLE
The icon of this extension in the penal did not follow the system icon theme.

### ISSUE THREAD

**Issue by huge-pancake** [oae/gnome-shell-pano#99]
**Describe the bug**
The icon of this extension in the penal did not follow the system icon theme.

**Expected behavior**
The extension's icon remains the same no matter what icon theme I use.

**Screenshots**
![image](https://user-images.githubusercontent.com/73375859/192074958-67b9d538-500d-4bf0-a043-e65efae2a7e7.png)

**To Reproduce**
- GNOME Shell version: 43
- Distro: Fedora 38 (Fedora Rawhide)
- Steps to reproduce, if applicable:
1. Download this extension
2. Change any icon theme

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
nothing...
```

**Comment by oae** [comment]
It doesn't use system icons. Pano provides its own icon.

**Comment by huge-pancake** [comment]
So, can it give a option to let user choose that use it own icon or icon in system icon pack?

**Comment by oae** [comment]
You can change the SVG file and relog, you will see the new icon.

- Path for indicator: `~/.local/share/gnome-shell/extensions/pano@elhan.io/icons/indicator.svg`
- Path for incognito indicator: `~/.local/share/gnome-shell/extensions/pano@elhan.io/icons/indicator-incognito.svg`
